/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aditya Pandey
 */
public class Authorised_Strength extends javax.swing.JFrame {

    private boolean go_back;

    //Creates new form authorized_Strength
    private int mouseX, mouseY;
    Database db = new Database();
    Connection con = db.create_connection(true);

    public Authorised_Strength() {

        initComponents();
        
        
        //for a centered frame
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        //for a centered frame
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT count(*) as count FROM auth_strength");
            int count = 0;
            while (rs.next()) {
                count = rs.getInt("count");
            }
            if (count == 0) {
                stmt.executeUpdate("Insert into auth_strength values(0,0)");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

        view();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        move_panel = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        minimize_icon = new javax.swing.JLabel();
        exit_icon = new javax.swing.JLabel();
        side_pane = new javax.swing.JPanel();
        title_separator = new javax.swing.JSeparator();
        go_back_label = new javax.swing.JLabel();
        menuA = new javax.swing.JPanel();
        menuA_icon = new javax.swing.JLabel();
        menuA_label = new javax.swing.JLabel();
        menuB = new javax.swing.JPanel();
        menuB_icon = new javax.swing.JLabel();
        menuB_label = new javax.swing.JLabel();
        title_label1 = new javax.swing.JLabel();
        title_label = new javax.swing.JLabel();
        title_icon = new javax.swing.JLabel();
        panelA = new javax.swing.JPanel();
        total_battalion_strengthA = new javax.swing.JLabel();
        total_battalion_strength_labelA = new javax.swing.JLabel();
        company_strength_labelA = new javax.swing.JLabel();
        company_strengthA = new javax.swing.JLabel();
        separatorA = new javax.swing.JSeparator();
        edit_buttonA = new javax.swing.JPanel();
        edit_labelA = new javax.swing.JLabel();
        panelB = new javax.swing.JPanel();
        service_number_label1 = new javax.swing.JLabel();
        update_buttonB = new javax.swing.JPanel();
        update_labelB = new javax.swing.JLabel();
        total_battalion_strength_underlineB = new javax.swing.JSeparator();
        total_battalion_strength_textfieldB = new javax.swing.JTextField();
        company_strength_underlineB = new javax.swing.JSeparator();
        company_strength_textfieldB = new javax.swing.JTextField();
        company_strength_labelB = new javax.swing.JLabel();
        separatorB = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(0, 0));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1280, 720));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        move_panel.setFocusable(false);
        move_panel.setOpaque(false);
        move_panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                move_panelMouseDragged(evt);
            }
        });
        move_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                move_panelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout move_panelLayout = new javax.swing.GroupLayout(move_panel);
        move_panel.setLayout(move_panelLayout);
        move_panelLayout.setHorizontalGroup(
            move_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        move_panelLayout.setVerticalGroup(
            move_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(move_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 30));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMaximumSize(new java.awt.Dimension(1280, 720));
        bg.setMinimumSize(new java.awt.Dimension(1280, 720));
        bg.setPreferredSize(new java.awt.Dimension(1280, 720));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGS/minimize-purple.png"))); // NOI18N
        minimize_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_iconMouseClicked(evt);
            }
        });
        bg.add(minimize_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, -1, 40));

        exit_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGS/remove_purple.png"))); // NOI18N
        exit_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_iconMouseClicked(evt);
            }
        });
        bg.add(exit_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1215, 30, -1, -1));

        side_pane.setBackground(new java.awt.Color(54, 33, 89));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane.add(title_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 260, 50));

        go_back_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGS/left-arrow.png"))); // NOI18N
        go_back_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                go_back_labelMouseClicked(evt);
            }
        });
        side_pane.add(go_back_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        menuA.setBackground(new java.awt.Color(85, 65, 118));
        menuA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAMouseClicked(evt);
            }
        });

        menuA_icon.setForeground(new java.awt.Color(255, 255, 255));
        menuA_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuA_icon.setText("A");

        menuA_label.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        menuA_label.setForeground(new java.awt.Color(255, 255, 255));
        menuA_label.setText("View");

        javax.swing.GroupLayout menuALayout = new javax.swing.GroupLayout(menuA);
        menuA.setLayout(menuALayout);
        menuALayout.setHorizontalGroup(
            menuALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuALayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(menuA_icon)
                .addGap(33, 33, 33)
                .addComponent(menuA_label))
        );
        menuALayout.setVerticalGroup(
            menuALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuALayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(menuALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuA_label, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(menuA_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        side_pane.add(menuA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 330, 60));

        menuB.setBackground(new java.awt.Color(64, 43, 100));
        menuB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBMouseClicked(evt);
            }
        });

        menuB_icon.setForeground(new java.awt.Color(255, 255, 255));
        menuB_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuB_icon.setText("B");

        menuB_label.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        menuB_label.setForeground(new java.awt.Color(255, 255, 255));
        menuB_label.setText("Edit");

        javax.swing.GroupLayout menuBLayout = new javax.swing.GroupLayout(menuB);
        menuB.setLayout(menuBLayout);
        menuBLayout.setHorizontalGroup(
            menuBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(menuB_icon)
                .addGap(33, 33, 33)
                .addComponent(menuB_label)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        menuBLayout.setVerticalGroup(
            menuBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuB_label, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(menuB_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        side_pane.add(menuB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 320, 60));

        title_label1.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        title_label1.setForeground(new java.awt.Color(255, 255, 255));
        title_label1.setText("Authorised");
        side_pane.add(title_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 160, 40));

        title_label.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        title_label.setForeground(new java.awt.Color(255, 255, 255));
        title_label.setText("Strength");
        side_pane.add(title_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 170, 40));

        title_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGS/strength white.png"))); // NOI18N
        side_pane.add(title_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 70, 90));

        bg.add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 740));

        panelA.setBackground(new java.awt.Color(255, 255, 255));
        panelA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        total_battalion_strengthA.setFont(new java.awt.Font("Roboto Bk", 0, 24)); // NOI18N
        total_battalion_strengthA.setForeground(new java.awt.Color(54, 33, 89));
        total_battalion_strengthA.setText("> XXXXXXX");
        panelA.add(total_battalion_strengthA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        total_battalion_strength_labelA.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        total_battalion_strength_labelA.setForeground(new java.awt.Color(51, 51, 51));
        total_battalion_strength_labelA.setText("Total Battalion Strength");
        panelA.add(total_battalion_strength_labelA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, 40));

        company_strength_labelA.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        company_strength_labelA.setForeground(new java.awt.Color(51, 51, 51));
        company_strength_labelA.setText("Company Strength");
        panelA.add(company_strength_labelA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, 40));

        company_strengthA.setFont(new java.awt.Font("Roboto Bk", 0, 24)); // NOI18N
        company_strengthA.setForeground(new java.awt.Color(54, 33, 89));
        company_strengthA.setText("> XXXXXXX");
        panelA.add(company_strengthA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        separatorA.setForeground(new java.awt.Color(54, 33, 89));
        separatorA.setPreferredSize(new java.awt.Dimension(50, 20));
        panelA.add(separatorA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 192, 880, 10));

        edit_buttonA.setForeground(new java.awt.Color(240, 240, 240));
        edit_buttonA.setMaximumSize(new java.awt.Dimension(95, 25));
        edit_buttonA.setMinimumSize(new java.awt.Dimension(95, 25));
        edit_buttonA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_buttonAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                edit_buttonAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                edit_buttonAMouseExited(evt);
            }
        });
        edit_buttonA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edit_labelA.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        edit_labelA.setForeground(new java.awt.Color(64, 43, 100));
        edit_labelA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit_labelA.setText("EDIT");
        edit_buttonA.add(edit_labelA, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 13, 71, 24));

        panelA.add(edit_buttonA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 180, 50));

        bg.add(panelA, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, -2, 980, 740));

        panelB.setBackground(new java.awt.Color(255, 255, 255));
        panelB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        service_number_label1.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        service_number_label1.setForeground(new java.awt.Color(51, 51, 51));
        service_number_label1.setText("Total Battalion Strength");
        panelB.add(service_number_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, 40));

        update_buttonB.setForeground(new java.awt.Color(240, 240, 240));
        update_buttonB.setMaximumSize(new java.awt.Dimension(180, 50));
        update_buttonB.setMinimumSize(new java.awt.Dimension(180, 50));
        update_buttonB.setPreferredSize(new java.awt.Dimension(180, 50));
        update_buttonB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_buttonBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                update_buttonBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                update_buttonBMouseExited(evt);
            }
        });
        update_buttonB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        update_labelB.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        update_labelB.setForeground(new java.awt.Color(64, 43, 100));
        update_labelB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        update_labelB.setText("UPDATE");
        update_buttonB.add(update_labelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 0, 60, 50));

        panelB.add(update_buttonB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 180, 50));

        total_battalion_strength_underlineB.setForeground(new java.awt.Color(54, 33, 89));
        panelB.add(total_battalion_strength_underlineB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 400, 10));

        total_battalion_strength_textfieldB.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        total_battalion_strength_textfieldB.setForeground(new java.awt.Color(54, 33, 89));
        total_battalion_strength_textfieldB.setBorder(null);
        total_battalion_strength_textfieldB.setMargin(new java.awt.Insets(2, 4, 2, 2));
        total_battalion_strength_textfieldB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                total_battalion_strength_textfieldBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                total_battalion_strength_textfieldBFocusLost(evt);
            }
        });
        panelB.add(total_battalion_strength_textfieldB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 400, 40));

        company_strength_underlineB.setForeground(new java.awt.Color(54, 33, 89));
        panelB.add(company_strength_underlineB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 400, 10));

        company_strength_textfieldB.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        company_strength_textfieldB.setForeground(new java.awt.Color(54, 33, 89));
        company_strength_textfieldB.setBorder(null);
        company_strength_textfieldB.setMargin(new java.awt.Insets(2, 4, 2, 2));
        company_strength_textfieldB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                company_strength_textfieldBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                company_strength_textfieldBFocusLost(evt);
            }
        });
        company_strength_textfieldB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                company_strength_textfieldBMouseClicked(evt);
            }
        });
        panelB.add(company_strength_textfieldB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 400, 40));

        company_strength_labelB.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        company_strength_labelB.setForeground(new java.awt.Color(51, 51, 51));
        company_strength_labelB.setText("Company Strength");
        panelB.add(company_strength_labelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, 40));

        separatorB.setForeground(new java.awt.Color(54, 33, 89));
        separatorB.setPreferredSize(new java.awt.Dimension(50, 20));
        panelB.add(separatorB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 192, 880, 10));

        bg.add(panelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, -2, 990, 740));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void view() {
        int bs = 0, cs = 0;
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("Select * from auth_strength");

            while (rs.next()) {
                bs = rs.getInt("bat_Strength");
                cs = rs.getInt("Company_strength");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        total_battalion_strengthA.setText(Integer.toString(bs));
        company_strengthA.setText(Integer.toString(cs));
    }


    private void minimize_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_iconMouseClicked
        setState(this.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_minimize_iconMouseClicked

    private void exit_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_iconMouseClicked
        int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit the program?", "Exit Program", JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            dispose();
            db.create_connection(false);
        }
    }//GEN-LAST:event_exit_iconMouseClicked

    private void go_back_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_go_back_labelMouseClicked
        if (go_back) {
            new Parade_Module().setVisible(true);
            this.setVisible(false);
        }
        go_back = false;
    }//GEN-LAST:event_go_back_labelMouseClicked

    private void menuAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAMouseClicked
        menuA.setBackground(new java.awt.Color(85, 65, 118));
        menuB.setBackground(new java.awt.Color(64, 43, 100));

        panelA.setVisible(true);
        panelB.setVisible(false);

        view();
    }//GEN-LAST:event_menuAMouseClicked

    private void menuBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBMouseClicked
        menuB.setBackground(new java.awt.Color(85, 65, 118));
        menuA.setBackground(new java.awt.Color(64, 43, 100));

        panelA.setVisible(false);
        panelB.setVisible(true);

        int bs = 0, cs = 0;
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("Select * from auth_strength");

            while (rs.next()) {
                bs = rs.getInt("bat_Strength");
                cs = rs.getInt("Company_strength");
            }
        } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);

        }

        if (total_battalion_strength_textfieldB.getText().equals("")) {
            total_battalion_strength_textfieldB.setText(Integer.toString(bs));
            total_battalion_strength_textfieldB.setForeground(Color.decode("#a9a9a9"));
        }
        if (company_strength_textfieldB.getText().equals("")) {
            company_strength_textfieldB.setText(Integer.toString(cs));
            company_strength_textfieldB.setForeground(Color.decode("#a9a9a9"));
        }
    }//GEN-LAST:event_menuBMouseClicked

    private void edit_buttonAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_buttonAMouseClicked
        menuBMouseClicked(null);
        
        
    }//GEN-LAST:event_edit_buttonAMouseClicked

    private void edit_buttonAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_buttonAMouseEntered
        edit_buttonA.setBackground(new java.awt.Color(237, 224, 255));// TODO add your handling code here:
    }//GEN-LAST:event_edit_buttonAMouseEntered

    private void edit_buttonAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_buttonAMouseExited
        edit_buttonA.setBackground(new java.awt.Color(240, 240, 240));// TODO add your handling code here:
    }//GEN-LAST:event_edit_buttonAMouseExited

    private void update_buttonBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_buttonBMouseClicked
        // TODO add your handling code here:
        boolean flag = false;
        int bat_Strength = 0, comp_Strength = 0, bs = 0, cs = 0;
//        System.out.println("text:"+total_battalion_strength_textfieldB.getText()+"space");

        try {
            try {
                flag = true;
                bat_Strength = Integer.valueOf(total_battalion_strength_textfieldB.getText().trim());
                comp_Strength = Integer.valueOf(company_strength_textfieldB.getText().trim());

            } catch (Exception e) {

                flag = false;
                JOptionPane.showMessageDialog(null, "Please enter integer values", "Error", JOptionPane.ERROR_MESSAGE);
            }

            if (flag == true) {
                PreparedStatement pstmt = con.prepareStatement("Update auth_strength set bat_strength=?, company_strength=?");
                pstmt.setInt(1, bat_Strength);
                pstmt.setInt(2, comp_Strength);
                pstmt.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data insertion successful", "Successful", JOptionPane.WARNING_MESSAGE);
                
                company_strength_textfieldB.setForeground(Color.decode("#a9a9a9"));
                total_battalion_strength_textfieldB.setForeground(Color.decode("#a9a9a9"));
                menuAMouseClicked(null);
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_update_buttonBMouseClicked

    private void update_buttonBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_buttonBMouseEntered
        update_buttonB.setBackground(new java.awt.Color(237, 224, 255));// TODO add your handling code here:
    }//GEN-LAST:event_update_buttonBMouseEntered

    private void update_buttonBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_buttonBMouseExited
        update_buttonB.setBackground(new java.awt.Color(240, 240, 240));// TODO add your handling code here:
    }//GEN-LAST:event_update_buttonBMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //to set menuA be selected by default --- start
        panelA.setVisible(true);
        panelB.setVisible(false);

        menuA.setBackground(new java.awt.Color(85, 65, 118));
        menuB.setBackground(new java.awt.Color(64, 43, 100));
        go_back = true;
        //to set menuA be selected by default --- end
    }//GEN-LAST:event_formWindowOpened

    private void move_panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_move_panelMouseDragged
        this.setLocation(this.getX() + evt.getX() - mouseX, this.getY() + evt.getY() - mouseY);
    }//GEN-LAST:event_move_panelMouseDragged

    private void move_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_move_panelMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_move_panelMousePressed

    private void total_battalion_strength_textfieldBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_total_battalion_strength_textfieldBFocusGained
        try {   Statement s = con.createStatement();
                String query1 = "select * from auth_strength";
                ResultSet rs    = s.executeQuery(query1); // Retrieving last stored password in database
                String res = null;
                while (rs.next()) {
                    res = rs.getString("bat_strength"); // Storing previou password in String "res"
                    
                }
                if(total_battalion_strength_textfieldB.getText().equals(res)){
                    total_battalion_strength_textfieldB.setText("");
                    total_battalion_strength_textfieldB.setForeground(Color.decode("#000000"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(modify_parade_state.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_total_battalion_strength_textfieldBFocusGained

    private void company_strength_textfieldBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_company_strength_textfieldBMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_company_strength_textfieldBMouseClicked

    private void total_battalion_strength_textfieldBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_total_battalion_strength_textfieldBFocusLost
        // TODO add your handling code here:
        try {
                Statement s = con.createStatement();
                String query1 = "select * from auth_strength";
                ResultSet rs    = s.executeQuery(query1); // Retrieving last stored password in database
                String res = null;
                while (rs.next()) {
                    res = rs.getString("bat_strength"); // Storing previou password in String "res"
                    
                }
                if(total_battalion_strength_textfieldB.getText().equals("")){
                    total_battalion_strength_textfieldB.setText(res);
                    total_battalion_strength_textfieldB.setForeground(Color.decode("#a9a9a9"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(modify_parade_state.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_total_battalion_strength_textfieldBFocusLost

    private void company_strength_textfieldBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_company_strength_textfieldBFocusLost
        try {
                Statement s = con.createStatement();
                String query1 = "select * from auth_strength";
                ResultSet rs    = s.executeQuery(query1); // Retrieving last stored password in database
                String res = null;
                while (rs.next()) {
                    res = rs.getString("company_strength"); // Storing previou password in String "res"
                    
                }
                if(company_strength_textfieldB.getText().equals("")){
                    company_strength_textfieldB.setText(res);
                    company_strength_textfieldB.setForeground(Color.decode("#a9a9a9"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(modify_parade_state.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_company_strength_textfieldBFocusLost

    private void company_strength_textfieldBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_company_strength_textfieldBFocusGained
        // TODO add your handling code here:
        try {   Statement s = con.createStatement();
                String query1 = "select * from auth_strength";
                ResultSet rs    = s.executeQuery(query1); // Retrieving last stored password in database
                String res = null;
                while (rs.next()) {
                    res = rs.getString("company_strength"); // Storing previou password in String "res"
                    
                }
                if(company_strength_textfieldB.getText().equals(res)){
                    company_strength_textfieldB.setText("");
                    company_strength_textfieldB.setForeground(Color.decode("#000000"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(modify_parade_state.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_company_strength_textfieldBFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authorised_Strength.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authorised_Strength.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authorised_Strength.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authorised_Strength.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authorised_Strength().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel company_strengthA;
    private javax.swing.JLabel company_strength_labelA;
    private javax.swing.JLabel company_strength_labelB;
    private javax.swing.JTextField company_strength_textfieldB;
    private javax.swing.JSeparator company_strength_underlineB;
    private javax.swing.JPanel edit_buttonA;
    private javax.swing.JLabel edit_labelA;
    private javax.swing.JLabel exit_icon;
    private javax.swing.JLabel go_back_label;
    private javax.swing.JPanel menuA;
    private javax.swing.JLabel menuA_icon;
    private javax.swing.JLabel menuA_label;
    private javax.swing.JPanel menuB;
    private javax.swing.JLabel menuB_icon;
    private javax.swing.JLabel menuB_label;
    private javax.swing.JLabel minimize_icon;
    private javax.swing.JPanel move_panel;
    private javax.swing.JPanel panelA;
    private javax.swing.JPanel panelB;
    private javax.swing.JSeparator separatorA;
    private javax.swing.JSeparator separatorB;
    private javax.swing.JLabel service_number_label1;
    private javax.swing.JPanel side_pane;
    private javax.swing.JLabel title_icon;
    private javax.swing.JLabel title_label;
    private javax.swing.JLabel title_label1;
    private javax.swing.JSeparator title_separator;
    private javax.swing.JLabel total_battalion_strengthA;
    private javax.swing.JLabel total_battalion_strength_labelA;
    private javax.swing.JTextField total_battalion_strength_textfieldB;
    private javax.swing.JSeparator total_battalion_strength_underlineB;
    private javax.swing.JPanel update_buttonB;
    private javax.swing.JLabel update_labelB;
    // End of variables declaration//GEN-END:variables
}
