
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chise
 */
public class ERE_module extends javax.swing.JFrame {

    /**
     * Creates new form ERE_module
     */
    
    
    Database db=new Database();
    
    private int mouseX, mouseY;
    Connection c = db.create_connection(true);
    Statement s;
    
    boolean flag = true;
    public ERE_module() {
        initComponents();
        
        ScrollPaneA.getVerticalScrollBar().setUnitIncrement(16);
        
         try {
            s = c.createStatement();
        } catch (Exception ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        move_panel = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        exit_icon = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        Separator = new javax.swing.JSeparator();
        side_pane = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        go_back_label = new javax.swing.JLabel();
        menuA = new javax.swing.JPanel();
        menuA_icon = new javax.swing.JLabel();
        menuA_label = new javax.swing.JLabel();
        title_label = new javax.swing.JLabel();
        title_icon = new javax.swing.JLabel();
        ScrollPaneA = new javax.swing.JScrollPane();
        panelA = new javax.swing.JPanel();
        panelA_bottom_line2 = new javax.swing.JSeparator();
        relief_section_label = new javax.swing.JLabel();
        to_unit_textfield = new javax.swing.JTextField();
        service_number_underline = new javax.swing.JSeparator();
        service_number_textfield = new javax.swing.JTextField();
        service_number_label = new javax.swing.JLabel();
        okay = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        rank_label = new javax.swing.JLabel();
        rank = new javax.swing.JLabel();
        trade_label = new javax.swing.JLabel();
        trade = new javax.swing.JLabel();
        to_unit_underline = new javax.swing.JSeparator();
        midA1 = new javax.swing.JSeparator();
        SOS_label = new javax.swing.JLabel();
        SOS_textfield = new javax.swing.JTextField();
        SOS_underline = new javax.swing.JSeparator();
        tenure_label = new javax.swing.JLabel();
        tenure_textfield = new javax.swing.JTextField();
        tenure_underline = new javax.swing.JSeparator();
        to_unit_label = new javax.swing.JLabel();
        name_label1 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        rank_label1 = new javax.swing.JLabel();
        rank1 = new javax.swing.JLabel();
        company_label1 = new javax.swing.JLabel();
        company1 = new javax.swing.JLabel();
        trade_label1 = new javax.swing.JLabel();
        trade1 = new javax.swing.JLabel();
        unit_label1 = new javax.swing.JLabel();
        unit1 = new javax.swing.JLabel();
        in_months_label = new javax.swing.JLabel();
        service_number_underline1 = new javax.swing.JSeparator();
        service_number_textfield1 = new javax.swing.JTextField();
        service_number_label1 = new javax.swing.JLabel();
        okay1 = new javax.swing.JLabel();
        print_button = new javax.swing.JPanel();
        print_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        move_panel.setFocusable(false);
        move_panel.setOpaque(false);
        move_panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                move_panelMouseDragged(evt);
            }
        });
        move_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                move_panelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout move_panelLayout = new javax.swing.GroupLayout(move_panel);
        move_panel.setLayout(move_panelLayout);
        move_panelLayout.setHorizontalGroup(
            move_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        move_panelLayout.setVerticalGroup(
            move_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(move_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 30));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMaximumSize(new java.awt.Dimension(1280, 720));
        bg.setMinimumSize(new java.awt.Dimension(1280, 720));
        bg.setPreferredSize(new java.awt.Dimension(1280, 720));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGS/remove_purple.png"))); // NOI18N
        exit_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_iconMouseClicked(evt);
            }
        });
        bg.add(exit_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1215, 30, -1, -1));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGS/minimize-purple.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        bg.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, -1, 40));

        Separator.setForeground(new java.awt.Color(54, 33, 89));
        Separator.setPreferredSize(new java.awt.Dimension(50, 20));
        bg.add(Separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 890, 10));

        side_pane.setBackground(new java.awt.Color(54, 33, 89));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 280, 50));

        go_back_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGS/left-arrow.png"))); // NOI18N
        go_back_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                go_back_labelMouseClicked(evt);
            }
        });
        side_pane.add(go_back_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        menuA.setBackground(new java.awt.Color(85, 65, 118));
        menuA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAMouseClicked(evt);
            }
        });

        menuA_icon.setForeground(new java.awt.Color(255, 255, 255));
        menuA_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuA_icon.setText("A");

        menuA_label.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        menuA_label.setForeground(new java.awt.Color(255, 255, 255));
        menuA_label.setText("ERE");

        javax.swing.GroupLayout menuALayout = new javax.swing.GroupLayout(menuA);
        menuA.setLayout(menuALayout);
        menuALayout.setHorizontalGroup(
            menuALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuALayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(menuA_icon)
                .addGap(33, 33, 33)
                .addComponent(menuA_label)
                .addContainerGap(224, Short.MAX_VALUE))
        );
        menuALayout.setVerticalGroup(
            menuALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuALayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(menuALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuA_label, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(menuA_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        side_pane.add(menuA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 330, 60));

        title_label.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        title_label.setForeground(new java.awt.Color(255, 255, 255));
        title_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_label.setText("ERE");
        side_pane.add(title_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 80, 50));

        title_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGS/ERE_white.png"))); // NOI18N
        side_pane.add(title_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 80, 70));

        bg.add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 740));

        ScrollPaneA.setBorder(null);
        ScrollPaneA.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelA.setBackground(new java.awt.Color(255, 255, 255));
        panelA.setFocusable(false);
        panelA.setMaximumSize(new java.awt.Dimension(950, 1310));
        panelA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelA_bottom_line2.setForeground(new java.awt.Color(54, 33, 89));
        panelA.add(panelA_bottom_line2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 810, 910, 5));

        relief_section_label.setBackground(new java.awt.Color(255, 255, 255));
        relief_section_label.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        relief_section_label.setForeground(new java.awt.Color(51, 51, 51));
        relief_section_label.setText("As Relief Of");
        panelA.add(relief_section_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, 40));

        to_unit_textfield.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        to_unit_textfield.setForeground(new java.awt.Color(54, 33, 89));
        to_unit_textfield.setBorder(null);
        to_unit_textfield.setMargin(new java.awt.Insets(2, 4, 2, 2));
        to_unit_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                to_unit_textfieldActionPerformed(evt);
            }
        });
        panelA.add(to_unit_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 210, 40));

        service_number_underline.setForeground(new java.awt.Color(54, 33, 89));
        panelA.add(service_number_underline, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 400, 20));

        service_number_textfield.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        service_number_textfield.setForeground(new java.awt.Color(54, 33, 89));
        service_number_textfield.setBorder(null);
        service_number_textfield.setMargin(new java.awt.Insets(2, 4, 2, 2));
        service_number_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                service_number_textfieldKeyPressed(evt);
            }
        });
        panelA.add(service_number_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 400, 40));

        service_number_label.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        service_number_label.setForeground(new java.awt.Color(51, 51, 51));
        service_number_label.setText("Army Number");
        panelA.add(service_number_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, 40));

        okay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGS/check-mark.png"))); // NOI18N
        okay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okayMouseClicked(evt);
            }
        });
        panelA.add(okay, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, 40));

        name_label.setBackground(new java.awt.Color(255, 255, 255));
        name_label.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        name_label.setForeground(new java.awt.Color(51, 51, 51));
        name_label.setText("Name");
        panelA.add(name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 40));

        name.setFont(new java.awt.Font("Roboto Bk", 0, 24)); // NOI18N
        name.setForeground(new java.awt.Color(54, 33, 89));
        name.setText("> XXXXXXX");
        panelA.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, 30));

        rank_label.setBackground(new java.awt.Color(255, 255, 255));
        rank_label.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        rank_label.setForeground(new java.awt.Color(51, 51, 51));
        rank_label.setText("Rank");
        panelA.add(rank_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, 40));

        rank.setFont(new java.awt.Font("Roboto Bk", 0, 24)); // NOI18N
        rank.setForeground(new java.awt.Color(54, 33, 89));
        rank.setText("> XXXXXXX");
        panelA.add(rank, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, 30));

        trade_label.setBackground(new java.awt.Color(255, 255, 255));
        trade_label.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        trade_label.setForeground(new java.awt.Color(51, 51, 51));
        trade_label.setText("Trade");
        panelA.add(trade_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, -1, 40));

        trade.setFont(new java.awt.Font("Roboto Bk", 0, 24)); // NOI18N
        trade.setForeground(new java.awt.Color(54, 33, 89));
        trade.setText("> XXXXXXX");
        panelA.add(trade, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, -1, 30));

        to_unit_underline.setForeground(new java.awt.Color(54, 33, 89));
        panelA.add(to_unit_underline, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 210, 20));

        midA1.setForeground(new java.awt.Color(204, 204, 255));
        panelA.add(midA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 480, 10));

        SOS_label.setBackground(new java.awt.Color(255, 255, 255));
        SOS_label.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        SOS_label.setForeground(new java.awt.Color(51, 51, 51));
        SOS_label.setText("SOS");
        panelA.add(SOS_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, 40));

        SOS_textfield.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        SOS_textfield.setForeground(new java.awt.Color(54, 33, 89));
        SOS_textfield.setBorder(null);
        SOS_textfield.setMargin(new java.awt.Insets(2, 4, 2, 2));
        SOS_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SOS_textfieldActionPerformed(evt);
            }
        });
        panelA.add(SOS_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 210, 40));

        SOS_underline.setForeground(new java.awt.Color(54, 33, 89));
        panelA.add(SOS_underline, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 210, 20));

        tenure_label.setBackground(new java.awt.Color(255, 255, 255));
        tenure_label.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        tenure_label.setForeground(new java.awt.Color(51, 51, 51));
        tenure_label.setText("Tenure");
        panelA.add(tenure_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, -1, 40));

        tenure_textfield.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        tenure_textfield.setForeground(new java.awt.Color(54, 33, 89));
        tenure_textfield.setBorder(null);
        tenure_textfield.setMargin(new java.awt.Insets(2, 4, 2, 2));
        tenure_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenure_textfieldActionPerformed(evt);
            }
        });
        panelA.add(tenure_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 210, 40));

        tenure_underline.setForeground(new java.awt.Color(54, 33, 89));
        panelA.add(tenure_underline, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 210, 10));

        to_unit_label.setBackground(new java.awt.Color(255, 255, 255));
        to_unit_label.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        to_unit_label.setForeground(new java.awt.Color(51, 51, 51));
        to_unit_label.setText("To Unit");
        panelA.add(to_unit_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 40));

        name_label1.setBackground(new java.awt.Color(255, 255, 255));
        name_label1.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        name_label1.setForeground(new java.awt.Color(51, 51, 51));
        name_label1.setText("Name");
        panelA.add(name_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, -1, 40));

        name1.setFont(new java.awt.Font("Roboto Bk", 0, 24)); // NOI18N
        name1.setForeground(new java.awt.Color(54, 33, 89));
        name1.setText("> XXXXXXX");
        panelA.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, -1, 30));

        rank_label1.setBackground(new java.awt.Color(255, 255, 255));
        rank_label1.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        rank_label1.setForeground(new java.awt.Color(51, 51, 51));
        rank_label1.setText("Rank");
        panelA.add(rank_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, -1, 40));

        rank1.setFont(new java.awt.Font("Roboto Bk", 0, 24)); // NOI18N
        rank1.setForeground(new java.awt.Color(54, 33, 89));
        rank1.setText("> XXXXXXX");
        panelA.add(rank1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, -1, 30));

        company_label1.setBackground(new java.awt.Color(255, 255, 255));
        company_label1.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        company_label1.setForeground(new java.awt.Color(51, 51, 51));
        company_label1.setText("Company");
        panelA.add(company_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 680, -1, 40));

        company1.setFont(new java.awt.Font("Roboto Bk", 0, 24)); // NOI18N
        company1.setForeground(new java.awt.Color(54, 33, 89));
        company1.setText("> XXXXXXX");
        panelA.add(company1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 720, -1, 30));

        trade_label1.setBackground(new java.awt.Color(255, 255, 255));
        trade_label1.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        trade_label1.setForeground(new java.awt.Color(51, 51, 51));
        trade_label1.setText("Trade");
        panelA.add(trade_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 590, -1, 40));

        trade1.setFont(new java.awt.Font("Roboto Bk", 0, 24)); // NOI18N
        trade1.setForeground(new java.awt.Color(54, 33, 89));
        trade1.setText("> XXXXXXX");
        panelA.add(trade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 630, -1, 30));

        unit_label1.setBackground(new java.awt.Color(255, 255, 255));
        unit_label1.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        unit_label1.setForeground(new java.awt.Color(51, 51, 51));
        unit_label1.setText("Unit");
        panelA.add(unit_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 680, -1, 40));

        unit1.setFont(new java.awt.Font("Roboto Bk", 0, 24)); // NOI18N
        unit1.setForeground(new java.awt.Color(54, 33, 89));
        unit1.setText("> XXXXXXX");
        panelA.add(unit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 720, -1, 30));

        in_months_label.setText("(in months)");
        panelA.add(in_months_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, -1, -1));

        service_number_underline1.setForeground(new java.awt.Color(54, 33, 89));
        panelA.add(service_number_underline1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 400, 20));

        service_number_textfield1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        service_number_textfield1.setForeground(new java.awt.Color(54, 33, 89));
        service_number_textfield1.setBorder(null);
        service_number_textfield1.setMargin(new java.awt.Insets(2, 4, 2, 2));
        service_number_textfield1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                service_number_textfield1KeyPressed(evt);
            }
        });
        panelA.add(service_number_textfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 400, 40));

        service_number_label1.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        service_number_label1.setForeground(new java.awt.Color(51, 51, 51));
        service_number_label1.setText("Army Number");
        panelA.add(service_number_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, 40));

        okay1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGS/check-mark.png"))); // NOI18N
        okay1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okay1MouseClicked(evt);
            }
        });
        panelA.add(okay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, -1, 40));

        ScrollPaneA.setViewportView(panelA);

        bg.add(ScrollPaneA, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 192, 910, 480));

        print_button.setForeground(new java.awt.Color(240, 240, 240));
        print_button.setMaximumSize(new java.awt.Dimension(95, 25));
        print_button.setMinimumSize(new java.awt.Dimension(95, 25));
        print_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                print_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                print_buttonMouseExited(evt);
            }
        });
        print_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        print_label.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        print_label.setForeground(new java.awt.Color(64, 43, 100));
        print_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        print_label.setText("PRINT");
        print_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                print_labelMouseEntered(evt);
            }
        });
        print_button.add(print_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 13, 71, 24));

        bg.add(print_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 120, 180, 50));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void printRecord(JPanel panel){
        // Create PrinterJob Here
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        // Set Printer Job Name
        printerJob.setJobName("Print Record");
        // Set Printable
        printerJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                // Check If No Printable Content
                if(pageIndex > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                // Make 2D Graphics to map content
                Graphics2D graphics2D = (Graphics2D)graphics;
                graphics2D.translate(pageFormat.getImageableX()+10, pageFormat.getImageableY()+10);
                graphics2D.scale(0.68,0.7);
                
                // Now paint panel as graphics2D
                panel.paint(graphics2D);
                
                // return if page exists
                return Printable.PAGE_EXISTS;
            }
        });
        // Store printerDialog as boolean
        boolean returningResult = printerJob.printDialog();
        // check if dilog is showing
        if(returningResult){
            // Use try catch exeption for failure
            try{
                // Now call print method inside printerJob to print
                printerJob.print();
            }catch (PrinterException printerException){
                JOptionPane.showMessageDialog(this, "Print Error: " + printerException.getMessage());
            }
        }}
    
    private void move_panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_move_panelMouseDragged
        this.setLocation(this.getX() +evt.getX() -mouseX, this.getY() + evt.getY() -mouseY);
    }//GEN-LAST:event_move_panelMouseDragged

    private void move_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_move_panelMousePressed
        mouseX =evt.getX();
        mouseY =evt.getY();
    }//GEN-LAST:event_move_panelMousePressed

    private void exit_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_iconMouseClicked
        int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit the program?", "Exit Program", JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            dispose();
            db.create_connection(false);
        }
    }//GEN-LAST:event_exit_iconMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setState(this.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void go_back_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_go_back_labelMouseClicked
        if(flag){
        new Modules(0).setVisible(true);
        this.setVisible(false);
        flag = false;
        }
    }//GEN-LAST:event_go_back_labelMouseClicked

    private void menuAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAMouseClicked

    }//GEN-LAST:event_menuAMouseClicked

    private void to_unit_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to_unit_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_to_unit_textfieldActionPerformed

    private void okayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okayMouseClicked
        if(service_number_textfield.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please Enter Army Number");
            name.setText("> XXXXXXX");
            rank.setText("> XXXXXXX");
            trade.setText("> XXXXXXX");
            trade_label.setText("Trade");
            service_number_textfield.setText("");
        }
        else{
        try {
            // TODO add your handling code here:
            String query1 = "select * from new_registration where service_no = '"+service_number_textfield.getText()+"' ;";
            ResultSet rs    = s.executeQuery(query1); // Retrieving last stored password in database
             // Retrieving last stored password in database
             int i = 0;
            if(rs.next() == false){
                i = 1;
            }
            if(i==1){
            query1 = "select * from attach_in where Service_no = '"+service_number_textfield.getText()+"' ;";
            ResultSet rs1    = s.executeQuery(query1);
            
                if(rs1.next() == false){
                i = 2;
            }
            }
            if(i==2){
                query1 = "select * from post_in where Service_no = '"+service_number_textfield.getText()+"' ;";
                ResultSet rs1    = s.executeQuery(query1);
                if(rs1.next() ==false){
                i=3;
                JOptionPane.showMessageDialog(rootPane, "Invalid Army Number");
                service_number_textfield.setText("");
                name.setText("> XXXXXXX");
                rank.setText("> XXXXXXX");
                trade.setText("> XXXXXXX");
                trade_label.setText("Trade");
                service_number_textfield.setText("");
                }
            }
            if(i!=3){
                String[] r = new String[5];
                if(i==1){
                    query1 = "select * from attach_in where Service_no = '"+service_number_textfield.getText()+"' ;";
                    ResultSet rs1    = s.executeQuery(query1); 
                    while(rs1.next()){
                        r[0] = rs1.getString("name");
                        r[1] = rs1.getString("rank_");
                        r[2] = rs1.getString("trade");
                    }
                name.setText(r[0]);
                rank.setText(r[1]);
                trade.setText(r[2]);
                }
                if(i==2){
                    query1 = "select * from post_in where Service_no = '"+service_number_textfield.getText()+"' ;";
                    ResultSet rs1    = s.executeQuery(query1); 
                    while(rs1.next()){
                        r[0] = rs1.getString("name");
                        r[1] = rs1.getString("rank_");
                    }
                name.setText(r[0]);
                rank.setText(r[1]);
                trade.setText("> XXXXXXX");
                }
                else if(i==0){
                query1 = "select * from new_registration where service_no = '"+service_number_textfield.getText()+"' ;";
                    try {
                        rs    = s.executeQuery(query1);
                    } catch (SQLException ex) {
                        Logger.getLogger(ERE_module.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        while(rs.next()){
                            
                            r[0] = rs.getString("name");
                            r[1] = rs.getString("rank_");
                            
                            name.setText(r[0]);
                            rank.setText(r[1]);
                            trade.setText("> XXXXXXX");
                        }   } catch (SQLException ex) {
                        Logger.getLogger(ERE_module.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } 
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Update_data.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_okayMouseClicked

    private void print_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_labelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_print_labelMouseClicked

    private void print_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_labelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_print_labelMouseEntered

    private void print_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_buttonMouseClicked
        title_label.grabFocus();
        if(service_number_textfield.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please Enter Army Number");
            name.setText("> XXXXXXX");
            rank.setText("> XXXXXXX");
            trade.setText("> XXXXXXX");
            trade_label.setText("Trade");
            service_number_textfield.setText("");
        }
        else{
        try {
            // TODO add your handling code here:
            String query1 = "select * from new_registration where service_no = '"+service_number_textfield.getText()+"' ;";
            ResultSet rs    = s.executeQuery(query1); // Retrieving last stored password in database
             // Retrieving last stored password in database
             int i = 0;
            if(rs.next() == false){
                i = 1;
            }
            if(i==1){
            query1 = "select * from attach_in where Service_no = '"+service_number_textfield.getText()+"' ;";
            ResultSet rs1    = s.executeQuery(query1);
            
                if(rs1.next() == false){
                i = 2;
            }
            }
            if(i==2){
                query1 = "select * from post_in where Service_no = '"+service_number_textfield.getText()+"' ;";
                ResultSet rs1    = s.executeQuery(query1);
                if(rs1.next() ==false){
                i=3;
                JOptionPane.showMessageDialog(rootPane, "Invalid Army Number");
                service_number_textfield.setText("");
                name.setText("> XXXXXXX");
                rank.setText("> XXXXXXX");
                trade.setText("> XXXXXXX");
                trade_label.setText("Trade");
                service_number_textfield.setText("");
                }
            }
            if(i!=3){
                String[] r = new String[5];
                if(i==1){
                    query1 = "select * from attach_in where Service_no = '"+service_number_textfield.getText()+"' ;";
                    ResultSet rs1    = s.executeQuery(query1); 
                    while(rs1.next()){
                        r[0] = rs1.getString("name");
                        r[1] = rs1.getString("rank_");
                        r[2] = rs1.getString("trade");
                    }
                name.setText(r[0]);
                rank.setText(r[1]);
                trade.setText(r[2]);
                }
                if(i==2){
                    query1 = "select * from post_in where Service_no = '"+service_number_textfield.getText()+"' ;";
                    ResultSet rs1    = s.executeQuery(query1); 
                    while(rs1.next()){
                        r[0] = rs1.getString("name");
                        r[1] = rs1.getString("rank_");
                        r[3] = rs1.getString("company");
                    }
                name.setText(r[0]);
                rank.setText(r[1]);
                trade.setText("> XXXXXXX");
                }
                else if(i==0){
                query1 = "select * from new_registration where service_no = '"+service_number_textfield.getText()+"' ;";
                    rs    = s.executeQuery(query1);
                while(rs.next()){
                    r[0] = rs.getString("name");
                    r[1] = rs.getString("rank_");
                }
                name.setText(r[0]);
                rank.setText(r[1]);
                trade.setText("> XXXXXXX");
                } 
                if(service_number_textfield1.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please Enter Army Number in As relief of section");
            name1.setText("> XXXXXXX");
            rank1.setText("> XXXXXXX");
            trade1.setText("> XXXXXXX");
            company1.setText("> XXXXXXX");
            unit1.setText("> XXXXXXX");
            unit_label1.setText("Unit");
            trade_label1.setText("Trade");
            service_number_textfield1.setText("");
        }
        else{
        try {
            // TODO add your handling code here:
            query1 = "select * from new_registration where service_no = '"+service_number_textfield1.getText()+"' ;";
            rs    = s.executeQuery(query1); // Retrieving last stored password in database
             // Retrieving last stored password in database
             i = 0;
            if(rs.next() == false){
                i = 1;
            }
            if(i==1){
            query1 = "select * from attach_in where Service_no = '"+service_number_textfield1.getText()+"' ;";
            ResultSet rs1    = s.executeQuery(query1);
            
                if(rs1.next() == false){
                i = 2;
            }
            }
            if(i==2){
                query1 = "select * from post_in where Service_no = '"+service_number_textfield1.getText()+"' ;";
                ResultSet rs1    = s.executeQuery(query1);
                if(rs1.next() ==false){
                i=3;
                JOptionPane.showMessageDialog(rootPane, "Invalid Army Number in As relief of section");
                service_number_textfield1.setText("");
                name1.setText("> XXXXXXX");
                rank1.setText("> XXXXXXX");
                trade1.setText("> XXXXXXX");
                company1.setText("> XXXXXXX");
                unit1.setText("> XXXXXXX");
                unit_label1.setText("Unit");
                trade_label1.setText("Trade");
                service_number_textfield1.setText("");
                }
            }
            if(i!=3){
                r = new String[5];
                if(i==1){
                    query1 = "select * from attach_in where Service_no = '"+service_number_textfield1.getText()+"' ;";
                    ResultSet rs1    = s.executeQuery(query1); 
                    while(rs1.next()){
                        r[0] = rs1.getString("name");
                        r[1] = rs1.getString("rank_");
                        r[2] = rs1.getString("trade");
                        r[3] = rs1.getString("company");
                        r[4] = rs1.getString("unit");
                    }
                name1.setText(r[0]);
                rank1.setText(r[1]);
                trade1.setText(r[2]);
                company1.setText(r[3]);
                unit1.setText(r[4]);
                }
                if(i==2){
                    query1 = "select * from post_in where Service_no = '"+service_number_textfield1.getText()+"' ;";
                    ResultSet rs1    = s.executeQuery(query1); 
                    while(rs1.next()){
                        r[0] = rs1.getString("name");
                        r[1] = rs1.getString("rank_");
                        r[3] = rs1.getString("company");
                    }
                name1.setText(r[0]);
                rank1.setText(r[1]);
                trade1.setText("> XXXXXXX");
                company1.setText(r[3]);
                unit1.setText("> XXXXXXX");
                }
                else if(i==0){
                query1 = "select * from new_registration where service_no = '"+service_number_textfield1.getText()+"' ;";
                    rs    = s.executeQuery(query1);
                while(rs.next()){
                    r[0] = rs.getString("name");
                    r[1] = rs.getString("rank_");
                    r[2] = rs.getString("company");
                }
                name1.setText(r[0]);
                rank1.setText(r[1]);
                trade1.setText("> XXXXXXX");
                company1.setText(r[2]);
                unit1.setText("> XXXXXXX");
                } 
                
                boolean all_check = (to_unit_textfield.getText()!=null && !to_unit_textfield.getText().trim().isEmpty())&& (SOS_textfield.getText()!=null && !SOS_textfield.getText().trim().isEmpty())&& (tenure_textfield.getText()!=null && !tenure_textfield.getText().trim().isEmpty()) ;
                
                if(all_check && !(service_number_textfield.getText().trim().equals(service_number_textfield1.getText().trim()))){
                try{
                    printRecord(panelA);
        }
        catch(Exception e){
            System.err.format("Error! Cannot Print.", e.getMessage());
        }
                }
                else if(service_number_textfield.getText().trim().equals(service_number_textfield1.getText().trim())){
                    JOptionPane.showMessageDialog(null, "Both Army numbers are same");
                }
                else if(all_check == false){
                    JOptionPane.showMessageDialog(null, "Fields are Empty");
                    if((to_unit_textfield.getText()==null || to_unit_textfield.getText().trim().isEmpty())){
                        to_unit_textfield.grabFocus();
                    }
                    else if((SOS_textfield.getText()==null || SOS_textfield.getText().trim().isEmpty())){
                        SOS_textfield.grabFocus();
                    }
                    else if((tenure_textfield.getText()==null || tenure_textfield.getText().trim().isEmpty())){
                        tenure_textfield.grabFocus();
                    }
                    
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Update_data.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Update_data.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_print_buttonMouseClicked

    private void print_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_buttonMouseEntered
        print_button.setBackground(new java.awt.Color(237, 224, 255));
    }//GEN-LAST:event_print_buttonMouseEntered

    private void print_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_buttonMouseExited
        print_button.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_print_buttonMouseExited

    private void SOS_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SOS_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SOS_textfieldActionPerformed

    private void tenure_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenure_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenure_textfieldActionPerformed

    private void okay1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okay1MouseClicked
        // TODO add your handling code here:
        if(service_number_textfield1.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please Enter Army Number");
            name1.setText("> XXXXXXX");
            rank1.setText("> XXXXXXX");
            trade1.setText("> XXXXXXX");
            company1.setText("> XXXXXXX");
            unit1.setText("> XXXXXXX");
            unit_label1.setText("Unit");
            trade_label1.setText("Trade");
            service_number_textfield1.setText("");
        }
        else{
        try {
            // TODO add your handling code here:
            String query1 = "select * from new_registration where service_no = '"+service_number_textfield1.getText()+"' ;";
            ResultSet rs    = s.executeQuery(query1); // Retrieving last stored password in database
             // Retrieving last stored password in database
             int i = 0;
            if(rs.next() == false){
                i = 1;
            }
            if(i==1){
            query1 = "select * from attach_in where Service_no = '"+service_number_textfield1.getText()+"' ;";
            ResultSet rs1    = s.executeQuery(query1);
            
                if(rs1.next() == false){
                i = 2;
            }
            }
            if(i==2){
                query1 = "select * from post_in where Service_no = '"+service_number_textfield1.getText()+"' ;";
                ResultSet rs1    = s.executeQuery(query1);
                if(rs1.next() ==false){
                i=3;
                JOptionPane.showMessageDialog(rootPane, "Invalid Army Number");
                service_number_textfield1.setText("");
                name1.setText("> XXXXXXX");
                rank1.setText("> XXXXXXX");
                trade1.setText("> XXXXXXX");
                company1.setText("> XXXXXXX");
                unit1.setText("> XXXXXXX");
                unit_label1.setText("Unit");
                trade_label1.setText("Trade");
                service_number_textfield1.setText("");
                }
            }
            if(i!=3){
                String[] r = new String[5];
                if(i==1){
                    query1 = "select * from attach_in where Service_no = '"+service_number_textfield1.getText()+"' ;";
                    ResultSet rs1    = s.executeQuery(query1); 
                    while(rs1.next()){
                        r[0] = rs1.getString("name");
                        r[1] = rs1.getString("rank_");
                        r[2] = rs1.getString("trade");
                        r[3] = rs1.getString("company");
                        r[4] = rs1.getString("unit");
                    }
                name1.setText(r[0]);
                rank1.setText(r[1]);
                trade1.setText(r[2]);
                company1.setText(r[3]);
                unit1.setText(r[4]);
                }
                if(i==2){
                    query1 = "select * from post_in where Service_no = '"+service_number_textfield1.getText()+"' ;";
                    ResultSet rs1    = s.executeQuery(query1); 
                    while(rs1.next()){
                        r[0] = rs1.getString("name");
                        r[1] = rs1.getString("rank_");
                        r[3] = rs1.getString("company");
                    }
                name1.setText(r[0]);
                rank1.setText(r[1]);
                trade1.setText("> XXXXXXX");
                company1.setText(r[3]);
                unit1.setText("> XXXXXXX");
                }
                else if (i==0){
                    query1 = "select * from new_registration where service_no = '"+service_number_textfield1.getText()+"' ;";
                    rs    = s.executeQuery(query1);
                while(rs.next()){
                    r[0] = rs.getString("name");
                    r[1] = rs.getString("rank_");
                    r[2] = rs.getString("company");
                }
                name1.setText(r[0]);
                rank1.setText(r[1]);
                trade1.setText("> XXXXXXX");
                company1.setText(r[2]);
                unit1.setText("> XXXXXXX");
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Update_data.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_okay1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         //for a centered frame
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        //for a centered frame
      
    }//GEN-LAST:event_formWindowOpened

    private void service_number_textfield1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_service_number_textfield1KeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            okay1MouseClicked(null);
        }
    }//GEN-LAST:event_service_number_textfield1KeyPressed

    private void service_number_textfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_service_number_textfieldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            okayMouseClicked(null);
        }
    }//GEN-LAST:event_service_number_textfieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ERE_module.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ERE_module.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ERE_module.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ERE_module.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ERE_module().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SOS_label;
    private javax.swing.JTextField SOS_textfield;
    private javax.swing.JSeparator SOS_underline;
    private javax.swing.JScrollPane ScrollPaneA;
    private javax.swing.JSeparator Separator;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel company1;
    private javax.swing.JLabel company_label1;
    private javax.swing.JLabel exit_icon;
    private javax.swing.JLabel go_back_label;
    private javax.swing.JLabel in_months_label;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menuA;
    private javax.swing.JLabel menuA_icon;
    private javax.swing.JLabel menuA_label;
    private javax.swing.JSeparator midA1;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel move_panel;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel name_label1;
    private javax.swing.JLabel okay;
    private javax.swing.JLabel okay1;
    private javax.swing.JPanel panelA;
    private javax.swing.JSeparator panelA_bottom_line2;
    private javax.swing.JPanel print_button;
    private javax.swing.JLabel print_label;
    private javax.swing.JLabel rank;
    private javax.swing.JLabel rank1;
    private javax.swing.JLabel rank_label;
    private javax.swing.JLabel rank_label1;
    private javax.swing.JLabel relief_section_label;
    private javax.swing.JLabel service_number_label;
    private javax.swing.JLabel service_number_label1;
    private javax.swing.JTextField service_number_textfield;
    private javax.swing.JTextField service_number_textfield1;
    private javax.swing.JSeparator service_number_underline;
    private javax.swing.JSeparator service_number_underline1;
    private javax.swing.JPanel side_pane;
    private javax.swing.JLabel tenure_label;
    private javax.swing.JTextField tenure_textfield;
    private javax.swing.JSeparator tenure_underline;
    private javax.swing.JLabel title_icon;
    private javax.swing.JLabel title_label;
    private javax.swing.JLabel to_unit_label;
    private javax.swing.JTextField to_unit_textfield;
    private javax.swing.JSeparator to_unit_underline;
    private javax.swing.JLabel trade;
    private javax.swing.JLabel trade1;
    private javax.swing.JLabel trade_label;
    private javax.swing.JLabel trade_label1;
    private javax.swing.JLabel unit1;
    private javax.swing.JLabel unit_label1;
    // End of variables declaration//GEN-END:variables
}
