/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Saksham
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    private boolean go_back = true;
    private int mouseX, mouseY;
    private JLabel confirm_pass_label; // Confirm Password label
    private JLabel new_pass_label;
    private javax.swing.JSeparator textfield_underlineA2;
    private javax.swing.JSeparator textfield_underlineA3;
    private JTextField new_pass_field; //Text field for taking new  password
    private JTextField confirm_pass_field; // Text field for taking confirm password
    private JButton change_pass_button; // Change password button
    Database db = new Database();
    private Connection c = db.create_connection(true);
    Statement s;
   
    private int a;

    public login(int k) {
        initComponents();
        a = k;
        try {
            s = c.createStatement();
        } catch (Exception ex) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        move_panel = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        minimize_icon = new javax.swing.JLabel();
        exit_icon = new javax.swing.JLabel();
        side_pane = new javax.swing.JPanel();
        menuA = new javax.swing.JPanel();
        menuA_icon = new javax.swing.JLabel();
        menuA_label = new javax.swing.JLabel();
        title_label = new javax.swing.JLabel();
        title_seperator = new javax.swing.JSeparator();
        title_icon_label = new javax.swing.JLabel();
        go_back_label = new javax.swing.JLabel();
        menuB = new javax.swing.JPanel();
        menuB_icon = new javax.swing.JLabel();
        menuB_label = new javax.swing.JLabel();
        login_panel = new javax.swing.JPanel();
        enter_pass_label = new javax.swing.JLabel();
        textfield_underlineA = new javax.swing.JSeparator();
        login_button = new javax.swing.JPanel();
        login_button_label = new javax.swing.JLabel();
        password_field = new javax.swing.JPasswordField();
        forgot_pass = new javax.swing.JPanel();
        textfield_underlineA1 = new javax.swing.JSeparator();
        enter_button = new javax.swing.JPanel();
        enter_button_label = new javax.swing.JLabel();
        master_key_label = new javax.swing.JLabel();
        master_key_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1280, 720));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        move_panel.setFocusable(false);
        move_panel.setOpaque(false);
        move_panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                move_panelMouseDragged(evt);
            }
        });
        move_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                move_panelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout move_panelLayout = new javax.swing.GroupLayout(move_panel);
        move_panel.setLayout(move_panelLayout);
        move_panelLayout.setHorizontalGroup(
            move_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        move_panelLayout.setVerticalGroup(
            move_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(move_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 30));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMaximumSize(new java.awt.Dimension(1280, 720));
        bg.setMinimumSize(new java.awt.Dimension(1280, 720));
        bg.setPreferredSize(new java.awt.Dimension(1280, 720));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGS/minimize-purple.png"))); // NOI18N
        minimize_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_iconMouseClicked(evt);
            }
        });
        bg.add(minimize_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, -1, 40));

        exit_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGS/remove_purple.png"))); // NOI18N
        exit_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_iconMouseClicked(evt);
            }
        });
        bg.add(exit_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1215, 30, -1, -1));

        side_pane.setBackground(new java.awt.Color(54, 33, 89));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuA.setBackground(new java.awt.Color(85, 65, 118));
        menuA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                menuAFocusGained(evt);
            }
        });
        menuA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAMouseClicked(evt);
            }
        });

        menuA_icon.setForeground(new java.awt.Color(255, 255, 255));
        menuA_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuA_icon.setText("A");

        menuA_label.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        menuA_label.setForeground(new java.awt.Color(255, 255, 255));
        menuA_label.setText("Login");

        javax.swing.GroupLayout menuALayout = new javax.swing.GroupLayout(menuA);
        menuA.setLayout(menuALayout);
        menuALayout.setHorizontalGroup(
            menuALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuALayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(menuA_icon)
                .addGap(33, 33, 33)
                .addComponent(menuA_label))
        );
        menuALayout.setVerticalGroup(
            menuALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuALayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(menuALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuA_label, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(menuA_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        side_pane.add(menuA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 330, 60));

        title_label.setFont(new java.awt.Font("Montserrat", 0, 36)); // NOI18N
        title_label.setForeground(new java.awt.Color(255, 255, 255));
        title_label.setText("Login");
        side_pane.add(title_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 125, 110, 50));
        side_pane.add(title_seperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 260, 50));

        title_icon_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_icon_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGS/login.png"))); // NOI18N
        side_pane.add(title_icon_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 115, 70, 70));

        go_back_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGS/left-arrow.png"))); // NOI18N
        go_back_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                go_back_labelMouseClicked(evt);
            }
        });
        side_pane.add(go_back_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        menuB.setBackground(new java.awt.Color(64, 43, 100));
        menuB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBMouseClicked(evt);
            }
        });

        menuB_icon.setForeground(new java.awt.Color(255, 255, 255));
        menuB_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuB_icon.setText("B");

        menuB_label.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        menuB_label.setForeground(new java.awt.Color(255, 255, 255));
        menuB_label.setText("Forgot Password");

        javax.swing.GroupLayout menuBLayout = new javax.swing.GroupLayout(menuB);
        menuB.setLayout(menuBLayout);
        menuBLayout.setHorizontalGroup(
            menuBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(menuB_icon)
                .addGap(33, 33, 33)
                .addComponent(menuB_label)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        menuBLayout.setVerticalGroup(
            menuBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuB_label, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(menuB_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        side_pane.add(menuB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 320, 60));

        bg.add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 740));

        login_panel.setBackground(new java.awt.Color(255, 255, 255));
        login_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enter_pass_label.setFont(new java.awt.Font("Montserrat", 0, 32)); // NOI18N
        enter_pass_label.setText("Enter Password");
        login_panel.add(enter_pass_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        textfield_underlineA.setForeground(new java.awt.Color(54, 33, 89));
        login_panel.add(textfield_underlineA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 450, 20));

        login_button.setForeground(new java.awt.Color(240, 240, 240));
        login_button.setMaximumSize(new java.awt.Dimension(95, 25));
        login_button.setMinimumSize(new java.awt.Dimension(95, 25));
        login_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_buttonMouseExited(evt);
            }
        });
        login_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_button_label.setBackground(new java.awt.Color(64, 43, 100));
        login_button_label.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        login_button_label.setForeground(new java.awt.Color(64, 43, 100));
        login_button_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_button_label.setText("LOGIN");
        login_button.add(login_button_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 13, 60, 24));

        login_panel.add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 200, 50));

        password_field.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        password_field.setBorder(null);
        password_field.setPreferredSize(new java.awt.Dimension(450, 50));
        password_field.setSelectionColor(new java.awt.Color(85, 65, 118));
        password_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                password_fieldKeyPressed(evt);
            }
        });
        login_panel.add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 450, 50));

        bg.add(login_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, -2, 1010, 740));

        forgot_pass.setBackground(new java.awt.Color(255, 255, 255));
        forgot_pass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textfield_underlineA1.setForeground(new java.awt.Color(54, 33, 89));
        forgot_pass.add(textfield_underlineA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 450, 20));

        enter_button.setForeground(new java.awt.Color(240, 240, 240));
        enter_button.setMaximumSize(new java.awt.Dimension(95, 25));
        enter_button.setMinimumSize(new java.awt.Dimension(95, 25));
        enter_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enter_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enter_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enter_buttonMouseExited(evt);
            }
        });
        enter_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enter_button_label.setBackground(new java.awt.Color(64, 43, 100));
        enter_button_label.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        enter_button_label.setForeground(new java.awt.Color(64, 43, 100));
        enter_button_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enter_button_label.setText("ENTER");
        enter_button.add(enter_button_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 0, 90, 50));

        forgot_pass.add(enter_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 200, 50));

        master_key_label.setFont(new java.awt.Font("Montserrat", 0, 32)); // NOI18N
        master_key_label.setText("Enter Master Key");
        forgot_pass.add(master_key_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        master_key_field.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        master_key_field.setBorder(null);
        forgot_pass.add(master_key_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 450, 50));

        bg.add(forgot_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, -2, 1010, 740));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBMouseClicked
        menuB.setBackground(new java.awt.Color(85, 65, 118));
        menuA.setBackground(new java.awt.Color(64, 43, 100));

        login_panel.setVisible(false);
        forgot_pass.setVisible(true);
    }//GEN-LAST:event_menuBMouseClicked

    private void go_back_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_go_back_labelMouseClicked
        if (go_back) {
            new home(1).setVisible(true);
            this.setVisible(false);
        }
        go_back = false;
    }//GEN-LAST:event_go_back_labelMouseClicked

    private void menuAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAMouseClicked
        menuA.setBackground(new java.awt.Color(85, 65, 118));
        menuB.setBackground(new java.awt.Color(64, 43, 100));

        login_panel.setVisible(true);
        forgot_pass.setVisible(false);
    }//GEN-LAST:event_menuAMouseClicked

    private void menuAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_menuAFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAFocusGained

    private void login_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_buttonMouseEntered
        login_button.setBackground(new java.awt.Color(237, 224, 255));// TODO add your handling code here:
    }//GEN-LAST:event_login_buttonMouseEntered

    private void login_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_buttonMouseExited
        login_button.setBackground(new java.awt.Color(240, 240, 240));// TODO add your handling code here:
    }//GEN-LAST:event_login_buttonMouseExited

    private void login_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_buttonMouseClicked
        // TODO add you System.out.println("abcd");
        String res = null;

        Database db = new Database();

        String u = password_field.getText();

        String q = "select * from login";
            
        try {
            ResultSet rs    = s.executeQuery(q);
            if(rs.next() == false){
                s.executeUpdate("insert into login values('admin');");
            }
            rs = s.executeQuery(q);

            while (rs.next()) {
                res = rs.getString("password");
            }

            if (res.equals(u)) {
                password_field.setText("");

                if (a == 1) {
                    new Notify(1).setVisible(true);
                    this.setVisible(false);
                } else {
                    this.setVisible(false);
                    new Modules(0).setVisible(true);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Invalid login");
                new Modules(0).setVisible(false);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_login_buttonMouseClicked

    private void enter_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter_buttonMouseClicked
        char c = '0';
        String str = "";
        for (int i = 0; i <= 15; i++) {
            str = str + c;
            for (int j = 0; j < 5; j++) {
                c++;
            }
        }
        if (master_key_field.getText().equals(str)) {

            // Creating Enter new Password Label
            new_pass_label = new javax.swing.JLabel();
            new_pass_label.setFont(new java.awt.Font("Montserrat", 0, 32));
            new_pass_label.setForeground(new java.awt.Color(0, 0, 0));
            new_pass_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            new_pass_label.setText("Enter new Password:");
            forgot_pass.add(new_pass_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 282, 450, 60));

            // Creating Confirm Password Label
            confirm_pass_label = new javax.swing.JLabel();
            confirm_pass_label.setFont(new java.awt.Font("Montserrat", 0, 32));
            confirm_pass_label.setForeground(new java.awt.Color(0, 0, 0));
            confirm_pass_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            confirm_pass_label.setText("Confirm Password:");
            forgot_pass.add(confirm_pass_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 422, 450, 60));

            master_key_field.setVisible(false); //Hiding Master Key field 
            master_key_label.setVisible(false);
            textfield_underlineA1.setVisible(false);
            enter_button.setVisible(false); // Hiding Continue button

            new_pass_field = new javax.swing.JTextField();
            confirm_pass_field = new javax.swing.JTextField();
            change_pass_button = new javax.swing.JButton();
            textfield_underlineA2 = new javax.swing.JSeparator();
            textfield_underlineA3 = new javax.swing.JSeparator();

            textfield_underlineA2.setForeground(new java.awt.Color(54, 33, 89));
            forgot_pass.add(textfield_underlineA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 402, 450, 20));

            textfield_underlineA3.setForeground(new java.awt.Color(54, 33, 89));
            forgot_pass.add(textfield_underlineA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 542, 450, 20));
            // Creating change Password Button
            change_pass_button.setFont(new java.awt.Font("Roboto", 0, 14));
            change_pass_button.setText("CHANGE");
            change_pass_button.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    change_pass_buttonActionPerformed(evt);
                }
            });
            forgot_pass.add(change_pass_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 562, 180, 50));

            // Setting default text in  New Password textfield
            new_pass_field.setFont(new java.awt.Font("Tahoma", 0, 24));
            new_pass_field.setToolTipText(" ");
            new_pass_field.setBorder(null);
            new_pass_field.setAutoscrolls(false);
            new_pass_field.setText("New Password");
            new_pass_field.setForeground(Color.decode("#a9a9a9"));
            new_pass_field.setBackground(new java.awt.Color(255, 255, 255));
            forgot_pass.add(new_pass_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 342, 450, 60));
            new_pass_field.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    new_pass_field_FocusGained(evt);
                }

                public void focusLost(java.awt.event.FocusEvent evt) {
                    new_pass_field_FocusLost(evt);
                }
            });

            // Setting default text in Confirm Password textfield
            confirm_pass_field.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
            confirm_pass_field.setToolTipText(" ");
            confirm_pass_field.setBorder(null);
            confirm_pass_field.setAutoscrolls(false);
            confirm_pass_field.setBackground(new java.awt.Color(255, 255, 255));
            confirm_pass_field.setText("Confirm Password");
            confirm_pass_field.setForeground(Color.decode("#a9a9a9"));
            forgot_pass.add(confirm_pass_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 482, 450, 60));
            confirm_pass_field.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    confirm_pass_field_FocusGained(evt);
                }

                public void focusLost(java.awt.event.FocusEvent evt) {
                    confirm_pass_field_FocusLost(evt);
                }
            });
        } else {
            master_key_field.setText("");
            JOptionPane.showMessageDialog(rootPane, "INCORRECT MASTER KEY"); // Display message if entered master key is incorrect
        }
    }//GEN-LAST:event_enter_buttonMouseClicked

    private void enter_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter_buttonMouseEntered
        enter_button.setBackground(new java.awt.Color(237, 224, 255));// TODO add your handling code here:
    }//GEN-LAST:event_enter_buttonMouseEntered
    private void new_pass_field_FocusGained(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:
        // Whenever New Password Field gain focus It will set New Password to null if nothing is entered by user previously and change its color to black from grey
        new_pass_field.setForeground(Color.decode("#000000"));
        if (new_pass_field.getText().trim().equals("New Password")) {
            new_pass_field.setText("");
        }
    }

    private void new_pass_field_FocusLost(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:
        // Whenever New Password Field lost focus It will set New Password to "New Password" if nothing is entered by user and change its color to grey from black
        if (new_pass_field.getText().trim().equals("")) {
            new_pass_field.setText("New Password");
            new_pass_field.setForeground(Color.decode("#a9a9a9"));
        }
    }

    private void confirm_pass_field_FocusGained(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:
        // Whenever Confirm Password Field gain focus It will set Confirm Password to null if nothing is entered by user previously and change its color to black from grey
        confirm_pass_field.setForeground(Color.decode("#000000"));
        if (confirm_pass_field.getText().trim().equals("Confirm Password")) {
            confirm_pass_field.setText("");
        }
    }

    private void confirm_pass_field_FocusLost(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:
        // Whenever Confirm Password Field lost focus It will set Confirm Password to "Confirm Password" if nothing is entered by user and change its color to grey from black
        if (confirm_pass_field.getText().trim().equals("")) {
            confirm_pass_field.setText("Confirm Password");
            confirm_pass_field.setForeground(Color.decode("#a9a9a9"));
        }
    }
    private void enter_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter_buttonMouseExited
        enter_button.setBackground(new java.awt.Color(240, 240, 240));// TODO add your handling code here:
    }//GEN-LAST:event_enter_buttonMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //for a centered frame
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        //for a centered frame

        menuA.setBackground(new java.awt.Color(85, 65, 118));
        menuB.setBackground(new java.awt.Color(64, 43, 100));

        login_panel.setVisible(true);
        forgot_pass.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void minimize_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_iconMouseClicked
        setState(this.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_minimize_iconMouseClicked

    private void exit_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_iconMouseClicked
        int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit the program?", "Exit Program", JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_exit_iconMouseClicked

    private void move_panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_move_panelMouseDragged
        this.setLocation(this.getX() + evt.getX() - mouseX, this.getY() + evt.getY() - mouseY);
    }//GEN-LAST:event_move_panelMouseDragged

    private void move_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_move_panelMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_move_panelMousePressed

    private void password_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_fieldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            login_buttonMouseClicked(null);
        }
    }//GEN-LAST:event_password_fieldKeyPressed
    private void change_pass_buttonActionPerformed(java.awt.event.ActionEvent evt) { // Performing Action on change password button
        // Making connection with Mysql Database
        String res = null;

        Database db = new Database();
        try {

            String query1 = "select * from login";
            ResultSet rs = s.executeQuery(query1); // Retrieving last stored password in Database

            while (rs.next()) {
                res = rs.getString("password"); // Storing previou password in String "res"

            }

            // Checking if New password and confirm password entered by user is same or not
            if (new_pass_field.getText().trim().equals(confirm_pass_field.getText().trim())) {
                // Now if New password and confirm password entered by user is same then update it in Database
                String query = "update login set password = ? where password = ?";
                PreparedStatement preparedStmt = (PreparedStatement) c.prepareStatement(query); // Preparing Update Statement
                preparedStmt.setString(2, res);
                preparedStmt.setString(1, new_pass_field.getText());

                // execute the java preparedstatement
                preparedStmt.executeUpdate(); // Executing statement to change in Database

                new_pass_field.setText("New Password");
                confirm_pass_field.setText("Confirm Password");
                confirm_pass_field.setForeground(Color.decode("#a9a9a9"));
                new_pass_field.setForeground(Color.decode("#a9a9a9"));
                JOptionPane.showMessageDialog(rootPane, "PASSWORD CHANGED SUCCESSFULLY"); // Showing message that password is changed successfully
                new_pass_field.setText("New Password");
                confirm_pass_field.setText("Confirm Password");
                confirm_pass_field.setForeground(Color.decode("#a9a9a9"));
                new_pass_field.setForeground(Color.decode("#a9a9a9"));

                menuAMouseClicked(null);
                
                textfield_underlineA2.setVisible(false);
                textfield_underlineA3.setVisible(false);
                textfield_underlineA1.setVisible(true);
                master_key_field.setVisible(true);
                master_key_field.setText("");

                master_key_label.setVisible(true);
                enter_button.setVisible(true);
                new_pass_field.setVisible(false);
                confirm_pass_field.setVisible(false);
                new_pass_label.setVisible(false);
                confirm_pass_label.setVisible(false);
                change_pass_button.setVisible(false);
            } else {
                if (new_pass_field.getText().trim().equals("New Password") && confirm_pass_field.getText().trim().equals("Confirm Password") == false) {
                    // If string in New Password field is "New Password" that means nothing is entered by user

                    // So showing message that New Password field is empty
                    JOptionPane.showMessageDialog(rootPane, "NEW PASSWORD FIELD IS EMPTY");
                } else if (confirm_pass_field.getText().trim().equals("Confirm Password") && new_pass_field.getText().trim().equals("New Password") == false) {
                    // In Confirm Password field if string retrieved is "Confirm Password" tht means nothing entered by user

                    // Showing Message that Confirm Password field is empty
                    JOptionPane.showMessageDialog(rootPane, "CONFIRM PASSWORD FIELD IS EMPTY");
                } else if (new_pass_field.getText().trim().equals("New Password") && confirm_pass_field.getText().trim().equals("Confirm Password")) {
                    // If string in New Password field is "New Password" that means nothing is entered by user
                    // Same for Confirm Password field if string retrieved is "Confirm Password" tht means nothing entered by user

                    // Shoeing message that both the fields are empty
                    JOptionPane.showMessageDialog(rootPane, "BOTH THE FIELDS ARE EMPTY");
                } else {
                    // In this else the condition is that user entered something in Both the fields but New Password didn't Match with Confirm Password

                    // Showing message that New Password and Confirm Password Didn't Match
                    JOptionPane.showMessageDialog(rootPane, "NEW PASSWORD AND CONFIRM PASSWORD DIDN'T MATCH");
                }
            }
        } catch (SQLException ex) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel enter_button;
    private javax.swing.JLabel enter_button_label;
    private javax.swing.JLabel enter_pass_label;
    private javax.swing.JLabel exit_icon;
    private javax.swing.JPanel forgot_pass;
    private javax.swing.JLabel go_back_label;
    private javax.swing.JPanel login_button;
    private javax.swing.JLabel login_button_label;
    private javax.swing.JPanel login_panel;
    private javax.swing.JTextField master_key_field;
    private javax.swing.JLabel master_key_label;
    private javax.swing.JPanel menuA;
    private javax.swing.JLabel menuA_icon;
    private javax.swing.JLabel menuA_label;
    private javax.swing.JPanel menuB;
    private javax.swing.JLabel menuB_icon;
    private javax.swing.JLabel menuB_label;
    private javax.swing.JLabel minimize_icon;
    private javax.swing.JPanel move_panel;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JPanel side_pane;
    private javax.swing.JSeparator textfield_underlineA;
    private javax.swing.JSeparator textfield_underlineA1;
    private javax.swing.JLabel title_icon_label;
    private javax.swing.JLabel title_label;
    private javax.swing.JSeparator title_seperator;
    // End of variables declaration//GEN-END:variables
}
