/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Aditya Pandey
 */
public class Pension_Out extends javax.swing.JFrame {

    private boolean go_back = true;
    Database db = new Database();
   // db.create_tables();
    Connection con = db.create_connection(true);
    /**
     * Creates new form Pension_Out
     */
    private int mouseX, mouseY;
    boolean flag = true;
    DefaultTableModel model_fullscreen, model_table;

    public Pension_Out() {
        initComponents();
        
        ScrollPaneA.getVerticalScrollBar().setUnitIncrement(16);
        fullscreen_ScrollPane.getVerticalScrollBar().setUnitIncrement(16);

        menuA.setBackground(new java.awt.Color(85, 65, 118));
        menuB.setBackground(new java.awt.Color(64, 43, 100));

        print_buttonA.setVisible(true);
        refresh_buttonA.setVisible(true);
        fullscreen_buttonA.setVisible(true);
        add_buttonB.setVisible(false);

        fullscreen_panel.setVisible(false);
        panelA.setVisible(true);
        panelB.setVisible(false);

        model_fullscreen = (DefaultTableModel) fullscreen_table.getModel();
        model_table = (DefaultTableModel) Table.getModel();
        viewall();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        move_panel = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        minimize_icon = new javax.swing.JLabel();
        exit_icon = new javax.swing.JLabel();
        side_pane = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        go_back_label = new javax.swing.JLabel();
        menuA = new javax.swing.JPanel();
        menuA_icon = new javax.swing.JLabel();
        menuA_label = new javax.swing.JLabel();
        menuB = new javax.swing.JPanel();
        menuB_icon = new javax.swing.JLabel();
        menuB_label = new javax.swing.JLabel();
        title_icon = new javax.swing.JLabel();
        title_label = new javax.swing.JLabel();
        Separator = new javax.swing.JSeparator();
        panelA = new javax.swing.JPanel();
        ScrollPaneA = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        panelB = new javax.swing.JPanel();
        DOR_label = new javax.swing.JLabel();
        service_number_label = new javax.swing.JLabel();
        service_numberA = new javax.swing.JTextField();
        textfield_underlineA = new javax.swing.JSeparator();
        okayA = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        DOB_label = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        DOR_date_comboboxA = new javax.swing.JComboBox<>();
        DOR_month_comboboxA = new javax.swing.JComboBox<>();
        DOR_year_comboboxA = new javax.swing.JComboBox<>();
        add_buttonB = new javax.swing.JPanel();
        add_labelB = new javax.swing.JLabel();
        refresh_buttonA = new javax.swing.JPanel();
        refresh_labelD = new javax.swing.JLabel();
        print_buttonA = new javax.swing.JPanel();
        print_labelD = new javax.swing.JLabel();
        fullscreen_buttonA = new javax.swing.JPanel();
        fullscreen_labelA = new javax.swing.JLabel();
        fullscreen_panel = new javax.swing.JPanel();
        fullscreen_ScrollPane = new javax.swing.JScrollPane();
        fullscreen_table = new javax.swing.JTable();
        exit_fullscreen_button = new javax.swing.JPanel();
        exit_fullscreen_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(0, 0));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1280, 720));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        move_panel.setFocusable(false);
        move_panel.setOpaque(false);
        move_panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                move_panelMouseDragged(evt);
            }
        });
        move_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                move_panelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout move_panelLayout = new javax.swing.GroupLayout(move_panel);
        move_panel.setLayout(move_panelLayout);
        move_panelLayout.setHorizontalGroup(
            move_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        move_panelLayout.setVerticalGroup(
            move_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(move_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 30));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMaximumSize(new java.awt.Dimension(1280, 720));
        bg.setMinimumSize(new java.awt.Dimension(1280, 720));
        bg.setPreferredSize(new java.awt.Dimension(1280, 720));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGS/minimize-purple.png"))); // NOI18N
        minimize_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_iconMouseClicked(evt);
            }
        });
        bg.add(minimize_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, -1, 40));

        exit_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGS/remove_purple.png"))); // NOI18N
        exit_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_iconMouseClicked(evt);
            }
        });
        bg.add(exit_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1215, 30, -1, -1));

        side_pane.setBackground(new java.awt.Color(54, 33, 89));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        side_pane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 260, 50));

        go_back_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGS/left-arrow.png"))); // NOI18N
        go_back_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                go_back_labelMouseClicked(evt);
            }
        });
        side_pane.add(go_back_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        menuA.setBackground(new java.awt.Color(85, 65, 118));
        menuA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAMouseClicked(evt);
            }
        });

        menuA_icon.setForeground(new java.awt.Color(255, 255, 255));
        menuA_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuA_icon.setText("A");

        menuA_label.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        menuA_label.setForeground(new java.awt.Color(255, 255, 255));
        menuA_label.setText("View All");

        javax.swing.GroupLayout menuALayout = new javax.swing.GroupLayout(menuA);
        menuA.setLayout(menuALayout);
        menuALayout.setHorizontalGroup(
            menuALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuALayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(menuA_icon)
                .addGap(33, 33, 33)
                .addComponent(menuA_label))
        );
        menuALayout.setVerticalGroup(
            menuALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuALayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(menuALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuA_label, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(menuA_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        side_pane.add(menuA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 330, 60));

        menuB.setBackground(new java.awt.Color(64, 43, 100));
        menuB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBMouseClicked(evt);
            }
        });

        menuB_icon.setForeground(new java.awt.Color(255, 255, 255));
        menuB_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuB_icon.setText("B");

        menuB_label.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        menuB_label.setForeground(new java.awt.Color(255, 255, 255));
        menuB_label.setText("Add New");

        javax.swing.GroupLayout menuBLayout = new javax.swing.GroupLayout(menuB);
        menuB.setLayout(menuBLayout);
        menuBLayout.setHorizontalGroup(
            menuBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(menuB_icon)
                .addGap(33, 33, 33)
                .addComponent(menuB_label)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        menuBLayout.setVerticalGroup(
            menuBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuB_label, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(menuB_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        side_pane.add(menuB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 320, 60));

        title_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGS/pension out white.png"))); // NOI18N
        side_pane.add(title_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 70, 80));

        title_label.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        title_label.setForeground(new java.awt.Color(255, 255, 255));
        title_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_label.setText("Pension Out");
        side_pane.add(title_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 190, 40));

        bg.add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 740));

        Separator.setForeground(new java.awt.Color(54, 33, 89));
        Separator.setPreferredSize(new java.awt.Dimension(50, 20));
        bg.add(Separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 890, 10));

        panelA.setBackground(new java.awt.Color(255, 255, 255));
        panelA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScrollPaneA.setBackground(new java.awt.Color(255, 255, 255));
        ScrollPaneA.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Table.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.no", "Service Num", "Name", "Date of Joining", "Company"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.setFocusable(false);
        Table.setGridColor(new java.awt.Color(255, 255, 255));
        Table.setMaximumSize(new java.awt.Dimension(300, 60));
        Table.setMinimumSize(new java.awt.Dimension(300, 60));
        Table.setRowHeight(30);
        Table.setSelectionBackground(new java.awt.Color(54, 33, 89));
        ScrollPaneA.setViewportView(Table);
        if (Table.getColumnModel().getColumnCount() > 0) {
            Table.getColumnModel().getColumn(0).setMinWidth(50);
            Table.getColumnModel().getColumn(0).setPreferredWidth(50);
            Table.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        panelA.add(ScrollPaneA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 780, 420));

        bg.add(panelA, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 192, 910, 480));

        panelB.setBackground(new java.awt.Color(255, 255, 255));
        panelB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DOR_label.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        DOR_label.setForeground(new java.awt.Color(51, 51, 51));
        DOR_label.setText("Date of Retirement");
        panelB.add(DOR_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, 40));

        service_number_label.setBackground(new java.awt.Color(255, 255, 255));
        service_number_label.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        service_number_label.setForeground(new java.awt.Color(51, 51, 51));
        service_number_label.setText("Army Number");
        panelB.add(service_number_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        service_numberA.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        service_numberA.setForeground(new java.awt.Color(54, 33, 89));
        service_numberA.setBorder(null);
        service_numberA.setMargin(new java.awt.Insets(2, 4, 2, 2));
        service_numberA.setSelectionColor(new java.awt.Color(204, 204, 255));
        service_numberA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                service_numberAKeyPressed(evt);
            }
        });
        panelB.add(service_numberA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 400, 40));

        textfield_underlineA.setForeground(new java.awt.Color(54, 33, 89));
        panelB.add(textfield_underlineA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 400, 10));

        okayA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGS/check-mark.png"))); // NOI18N
        okayA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okayAMouseClicked(evt);
            }
        });
        panelB.add(okayA, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, 40));

        name_label.setBackground(new java.awt.Color(255, 255, 255));
        name_label.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        name_label.setForeground(new java.awt.Color(51, 51, 51));
        name_label.setText("Name");
        panelB.add(name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, 50));

        name.setFont(new java.awt.Font("Roboto Bk", 0, 24)); // NOI18N
        name.setForeground(new java.awt.Color(54, 33, 89));
        name.setText("> XXXXXXX");
        panelB.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, 30));

        DOB_label.setBackground(new java.awt.Color(255, 255, 255));
        DOB_label.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        DOB_label.setForeground(new java.awt.Color(51, 51, 51));
        DOB_label.setText("Date of Birth");
        panelB.add(DOB_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, 50));

        DOB.setFont(new java.awt.Font("Roboto Bk", 0, 24)); // NOI18N
        DOB.setForeground(new java.awt.Color(54, 33, 89));
        DOB.setText("> XXXXXXX");
        panelB.add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, 30));

        DOR_date_comboboxA.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        DOR_date_comboboxA.setForeground(new java.awt.Color(44, 62, 80));
        DOR_date_comboboxA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DD", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DOR_date_comboboxA.setBorder(null);
        panelB.add(DOR_date_comboboxA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 100, 40));

        DOR_month_comboboxA.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        DOR_month_comboboxA.setForeground(new java.awt.Color(44, 62, 80));
        DOR_month_comboboxA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MM", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        DOR_month_comboboxA.setBorder(null);
        panelB.add(DOR_month_comboboxA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 100, 40));

        DOR_year_comboboxA.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        DOR_year_comboboxA.setForeground(new java.awt.Color(44, 62, 80));
        DOR_year_comboboxA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YYYY", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099", "2100", " " }));
        DOR_year_comboboxA.setBorder(null);
        panelB.add(DOR_year_comboboxA, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 100, 40));

        bg.add(panelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 192, 910, 480));

        add_buttonB.setForeground(new java.awt.Color(240, 240, 240));
        add_buttonB.setMaximumSize(new java.awt.Dimension(200, 200));
        add_buttonB.setMinimumSize(new java.awt.Dimension(200, 200));
        add_buttonB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_buttonBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_buttonBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_buttonBMouseExited(evt);
            }
        });
        add_buttonB.setLayout(null);

        add_labelB.setBackground(new java.awt.Color(54, 33, 89));
        add_labelB.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        add_labelB.setForeground(new java.awt.Color(54, 33, 89));
        add_labelB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add_labelB.setText("ADD");
        add_buttonB.add(add_labelB);
        add_labelB.setBounds(30, 0, 120, 50);

        bg.add(add_buttonB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 120, 180, 50));

        refresh_buttonA.setForeground(new java.awt.Color(240, 240, 240));
        refresh_buttonA.setMaximumSize(new java.awt.Dimension(200, 200));
        refresh_buttonA.setMinimumSize(new java.awt.Dimension(200, 200));
        refresh_buttonA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refresh_buttonAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refresh_buttonAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refresh_buttonAMouseExited(evt);
            }
        });
        refresh_buttonA.setLayout(null);

        refresh_labelD.setBackground(new java.awt.Color(54, 33, 89));
        refresh_labelD.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        refresh_labelD.setForeground(new java.awt.Color(54, 33, 89));
        refresh_labelD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refresh_labelD.setText("REFRESH");
        refresh_buttonA.add(refresh_labelD);
        refresh_labelD.setBounds(50, 0, 80, 50);

        bg.add(refresh_buttonA, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, 180, 50));

        print_buttonA.setForeground(new java.awt.Color(240, 240, 240));
        print_buttonA.setMaximumSize(new java.awt.Dimension(200, 200));
        print_buttonA.setMinimumSize(new java.awt.Dimension(200, 200));
        print_buttonA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print_buttonAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                print_buttonAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                print_buttonAMouseExited(evt);
            }
        });
        print_buttonA.setLayout(null);

        print_labelD.setBackground(new java.awt.Color(54, 33, 89));
        print_labelD.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        print_labelD.setForeground(new java.awt.Color(54, 33, 89));
        print_labelD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        print_labelD.setText("PRINT");
        print_buttonA.add(print_labelD);
        print_labelD.setBounds(50, 0, 80, 50);

        bg.add(print_buttonA, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 180, 50));

        fullscreen_buttonA.setForeground(new java.awt.Color(240, 240, 240));
        fullscreen_buttonA.setMaximumSize(new java.awt.Dimension(200, 200));
        fullscreen_buttonA.setMinimumSize(new java.awt.Dimension(200, 200));
        fullscreen_buttonA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fullscreen_buttonAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fullscreen_buttonAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fullscreen_buttonAMouseExited(evt);
            }
        });
        fullscreen_buttonA.setLayout(null);

        fullscreen_labelA.setBackground(new java.awt.Color(54, 33, 89));
        fullscreen_labelA.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        fullscreen_labelA.setForeground(new java.awt.Color(54, 33, 89));
        fullscreen_labelA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullscreen_labelA.setText("FULLSCREEN");
        fullscreen_buttonA.add(fullscreen_labelA);
        fullscreen_labelA.setBounds(30, 0, 120, 50);

        bg.add(fullscreen_buttonA, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 120, 180, 50));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        fullscreen_panel.setBackground(new java.awt.Color(255, 255, 255));
        fullscreen_panel.setMaximumSize(new java.awt.Dimension(1280, 720));
        fullscreen_panel.setMinimumSize(new java.awt.Dimension(1280, 720));
        fullscreen_panel.setPreferredSize(new java.awt.Dimension(1280, 720));
        fullscreen_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fullscreen_ScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        fullscreen_ScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        fullscreen_table.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fullscreen_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.no", "Service Num", "Name", "Date of Joining", "Company", "Address", "Courses Done", "Medical Category", "Date of Retirement"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fullscreen_table.setFocusable(false);
        fullscreen_table.setGridColor(new java.awt.Color(255, 255, 255));
        fullscreen_table.setMaximumSize(new java.awt.Dimension(300, 60));
        fullscreen_table.setMinimumSize(new java.awt.Dimension(300, 60));
        fullscreen_table.setRowHeight(30);
        fullscreen_table.setSelectionBackground(new java.awt.Color(54, 33, 89));
        fullscreen_ScrollPane.setViewportView(fullscreen_table);
        if (fullscreen_table.getColumnModel().getColumnCount() > 0) {
            fullscreen_table.getColumnModel().getColumn(0).setMinWidth(50);
            fullscreen_table.getColumnModel().getColumn(0).setPreferredWidth(50);
            fullscreen_table.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        fullscreen_panel.add(fullscreen_ScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 1200, 580));

        exit_fullscreen_button.setForeground(new java.awt.Color(240, 240, 240));
        exit_fullscreen_button.setMaximumSize(new java.awt.Dimension(200, 200));
        exit_fullscreen_button.setMinimumSize(new java.awt.Dimension(200, 200));
        exit_fullscreen_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_fullscreen_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_fullscreen_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit_fullscreen_buttonMouseExited(evt);
            }
        });
        exit_fullscreen_button.setLayout(null);

        exit_fullscreen_label.setBackground(new java.awt.Color(54, 33, 89));
        exit_fullscreen_label.setFont(new java.awt.Font("Roboto Bk", 0, 14)); // NOI18N
        exit_fullscreen_label.setForeground(new java.awt.Color(54, 33, 89));
        exit_fullscreen_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit_fullscreen_label.setText("GO BACK");
        exit_fullscreen_button.add(exit_fullscreen_label);
        exit_fullscreen_label.setBounds(30, 0, 120, 50);

        fullscreen_panel.add(exit_fullscreen_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 640, 180, 50));

        getContentPane().add(fullscreen_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean validate_service_no() {
        boolean flag = false;
        try {
            Statement stmt = con.createStatement();
            String name1 = "", bdate = "";

            if (service_numberA.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Enter Army Number", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                String Query = "Select Name, birth_date from new_registration where Service_no = '" + service_numberA.getText() + "';";
                ResultSet rs = stmt.executeQuery(Query);
                while (rs.next()) {
                    flag = true;
                    name1 = rs.getString("Name");
                    bdate = rs.getString("Birth_date");
                }
                if (flag == false) {
                    JOptionPane.showMessageDialog(null, "Army Number does not exist", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    name.setText("> " + name1);
                    DOB.setText("> " + bdate);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        return flag;
    }

    private void viewall() {
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("Select service_no, Name, Joining_date, Company, Address, Courses_done, Medical_Category, retirement_date from pension_out;");
            String service_no, name, doj, company, courses, medical, address, dor;
            model_table.setRowCount(0);
            model_fullscreen.setRowCount(0);
            int counter=0;
            while (rs.next()) {
                counter=counter+1;
                service_no = rs.getString("service_no");
                name = rs.getString("Name");
                doj = rs.getString("Joining_date");
                company = rs.getString("Company");
                address = rs.getString("Address");
                courses = rs.getString("Courses_done");
                medical = rs.getString("Medical_Category");
                dor = rs.getString("Retirement_date");
                model_table.addRow(new Object[]{
                    counter,service_no,
                    name,
                    doj,
                    company
                });
                model_fullscreen.addRow(new Object[]{
                    counter,service_no,
                    name,
                    doj,
                    company,
                    address,
                    courses,
                    medical,
                    dor
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private String validate_date() {
        String day_ = (String) DOR_date_comboboxA.getSelectedItem();
        String month_ = (String) DOR_month_comboboxA.getSelectedItem();
        String year_ = (String) DOR_year_comboboxA.getSelectedItem();
        String Join_date = "";
        if (day_ == "DD" || month_ == "MM" || year_ == "YYYY") {
            JOptionPane.showMessageDialog(null, "Enter a Valid Date", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int day = Integer.parseInt(day_);
            int month = Integer.parseInt(month_);
            int year = Integer.parseInt(year_);
            boolean flag = false;
            if ((month == 1 || month == 3 || month == 5 || month == 7 || month == 8 || month == 10 || month == 12) && day <= 31) {
                flag = true;
            } else if ((month == 4 || month == 6 || month == 9 || month == 11) && day <= 30) {
                flag = true;
            } else if (month == 2 && ((year % 4 == 0 && day <= 29) || (year % 4 != 0 && day <= 28))) {
                flag = true;
            }
            if (flag == true) {
                Join_date = day_ + "-" + month_ + "-" + year_;
            } else {
                JOptionPane.showMessageDialog(null, "Enter a Valid Date", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        return Join_date;
    }

    private void minimize_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_iconMouseClicked
        setState(this.ICONIFIED);
    }//GEN-LAST:event_minimize_iconMouseClicked

    private void exit_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_iconMouseClicked
        int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit the program?", "Exit Program", JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            dispose();
            db.create_connection(false);
        }
    }//GEN-LAST:event_exit_iconMouseClicked

    private void go_back_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_go_back_labelMouseClicked
        if (go_back) {
            new Parade_Module().setVisible(true);
            this.setVisible(false);

        }
        go_back = false;

    }//GEN-LAST:event_go_back_labelMouseClicked

    private void menuAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAMouseClicked
        menuA.setBackground(new java.awt.Color(85, 65, 118));
        menuB.setBackground(new java.awt.Color(64, 43, 100));

        print_buttonA.setVisible(true);
        refresh_buttonA.setVisible(true);
        fullscreen_buttonA.setVisible(true);
        add_buttonB.setVisible(false);

        fullscreen_panel.setVisible(false);
        panelA.setVisible(true);
        panelB.setVisible(false);

        viewall();
    }//GEN-LAST:event_menuAMouseClicked

    private void menuBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBMouseClicked
        menuB.setBackground(new java.awt.Color(85, 65, 118));
        menuA.setBackground(new java.awt.Color(64, 43, 100));

        print_buttonA.setVisible(false);
        refresh_buttonA.setVisible(false);
        fullscreen_buttonA.setVisible(false);
        add_buttonB.setVisible(true);

        service_numberA.setText("");
        name.setText(">XXXXXXX");
        DOB.setText(">XXXXXXX");

        fullscreen_panel.setVisible(false);
        panelA.setVisible(false);
        panelB.setVisible(true);
    }//GEN-LAST:event_menuBMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //for a centered frame
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        //for a centered frame

        menuA.setBackground(new java.awt.Color(85, 65, 118));
        menuB.setBackground(new java.awt.Color(64, 43, 100));

        print_buttonA.setVisible(true);
        refresh_buttonA.setVisible(true);
        fullscreen_buttonA.setVisible(true);
        add_buttonB.setVisible(false);

        fullscreen_panel.setVisible(false);
        panelA.setVisible(true);
        panelB.setVisible(false);

    }//GEN-LAST:event_formWindowOpened

    private void exit_fullscreen_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_fullscreen_buttonMouseClicked
        fullscreen_panel.setVisible(false);
        bg.setVisible(true);
        service_numberA.setText("");
        name.setText(">XXXXXXX");
        DOB.setText(">XXXXXXX");

        DOR_date_comboboxA.setSelectedItem("DD");
        DOR_month_comboboxA.setSelectedItem("MM");
        DOR_year_comboboxA.setSelectedItem("YYYY");
    }//GEN-LAST:event_exit_fullscreen_buttonMouseClicked

    private void exit_fullscreen_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_fullscreen_buttonMouseEntered
        exit_fullscreen_button.setBackground(new java.awt.Color(237, 224, 255));
    }//GEN-LAST:event_exit_fullscreen_buttonMouseEntered

    private void exit_fullscreen_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_fullscreen_buttonMouseExited
        exit_fullscreen_button.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_exit_fullscreen_buttonMouseExited

    private void add_buttonBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonBMouseClicked

        if (validate_service_no()) {
            String valid_date = validate_date();
            try {
                if (!valid_date.equals("")) {
                    Statement stmt = con.createStatement();

                    PreparedStatement pstmt = con.prepareStatement("Insert into pension_out(service_no, Name, Rank_,Company,Courses_done,Address,Indl_Contact_No,Birth_date ,Joining_date , Medical_Category , Indl_ICard_Number , Indl_PAN, Indl_Aadhar, Indl_Email, Indl_Acc_No, Indl_Bank_Name, Indl_Bank_Branch, Indl_IFSC, NOK, Kin_Contact_No, Kin_Relation, Kin_PAN, Kin_Aadhar, Kin_Email, Kin_Acc_No, Kin_Bank_Name, Kin_Bank_Branch, Kin_IFSC) select * from new_registration where service_no=?");
                    pstmt.setString(1, service_numberA.getText());
                    pstmt.executeUpdate();
                    pstmt = con.prepareStatement("update pension_out set Retirement_date=? where service_no=?");
                    pstmt.setString(1, valid_date);
                    pstmt.setString(2, service_numberA.getText());
                    pstmt.executeUpdate();

                    pstmt = con.prepareStatement("Delete from new_registration where service_no=?");
                    pstmt.setString(1, service_numberA.getText());
                    pstmt.executeUpdate();
                    viewall();
                    fullscreen_panel.setVisible(true);
                    bg.setVisible(false);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);

            }
        }
    }//GEN-LAST:event_add_buttonBMouseClicked

    private void fullscreen_buttonAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullscreen_buttonAMouseClicked
        viewall();
        fullscreen_panel.setVisible(true);
        bg.setVisible(false);
    }//GEN-LAST:event_fullscreen_buttonAMouseClicked

    private void okayAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okayAMouseClicked
        // TODO add your handling code here:
        validate_service_no();
    }//GEN-LAST:event_okayAMouseClicked

    private void refresh_buttonAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refresh_buttonAMouseClicked
        // TODO add your handling code here:
        viewall();
    }//GEN-LAST:event_refresh_buttonAMouseClicked

    private void print_buttonAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_buttonAMouseEntered
        print_buttonA.setBackground(new java.awt.Color(237, 224, 255));
    }//GEN-LAST:event_print_buttonAMouseEntered

    private void move_panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_move_panelMouseDragged
        this.setLocation(this.getX() + evt.getX() - mouseX, this.getY() + evt.getY() - mouseY);
    }//GEN-LAST:event_move_panelMouseDragged

    private void move_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_move_panelMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_move_panelMousePressed

    private void print_buttonAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_buttonAMouseClicked
        title_label.grabFocus();
        try {
            Statement statement = con.createStatement();
            ResultSet resultSet = statement.executeQuery("select * from pension_out");
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet spreadsheet = null;
            spreadsheet = workbook.createSheet("Pension_out");

            XSSFRow row = spreadsheet.createRow(0);
            XSSFCell cell;
            cell = row.createCell(0);
            cell.setCellValue("Army No");
            cell = row.createCell(1);
            cell.setCellValue("Name");
            cell = row.createCell(2);
            cell.setCellValue("Rank");
            cell = row.createCell(3);
            cell.setCellValue("Company");
            cell = row.createCell(4);
            cell.setCellValue("Courses done");
            cell = row.createCell(5);
            cell.setCellValue("Address");
            cell = row.createCell(6);
            cell.setCellValue("Indl Contact No");
            cell = row.createCell(7);
            cell.setCellValue("Birth Date");
            cell = row.createCell(8);
            cell.setCellValue("Joining Date");
            cell = row.createCell(9);
            cell.setCellValue("Medical category");
            cell = row.createCell(10);
            cell.setCellValue("Indl Icard No");
            cell = row.createCell(11);
            cell.setCellValue("Indl Pan");
            cell = row.createCell(12);
            cell.setCellValue("Indl Aadhar");
            cell = row.createCell(13);
            cell.setCellValue("Indl Email");
            cell = row.createCell(14);
            cell.setCellValue("Indl Account No");
            cell = row.createCell(15);
            cell.setCellValue("Indl Bank Name");
            cell = row.createCell(16);
            cell.setCellValue("Indl Bank Branch");
            cell = row.createCell(17);
            cell.setCellValue("Indl IFSC");
            cell = row.createCell(18);
            cell.setCellValue("NOK");
            cell = row.createCell(19);
            cell.setCellValue("Kin Contact No");
            cell = row.createCell(20);
            cell.setCellValue("Kin Relation");
            cell = row.createCell(21);
            cell.setCellValue("Kin Pan");
            cell = row.createCell(22);
            cell.setCellValue("Kin Aadhar");
            cell = row.createCell(23);
            cell.setCellValue("Kin Email");
            cell = row.createCell(24);
            cell.setCellValue("Kin Account No");
            cell = row.createCell(25);
            cell.setCellValue("Kin Bank Name");
            cell = row.createCell(26);
            cell.setCellValue("Kin Bank Branch");
            cell = row.createCell(27);
            cell.setCellValue("Kin IFSC");
            cell = row.createCell(28);
            cell.setCellValue("Retirement Date");
            int i = 1;

            while (resultSet.next()) {
                row = spreadsheet.createRow(i);
                cell = row.createCell(0);
                cell.setCellValue(resultSet.getString("Service_No"));
                cell = row.createCell(1);
                cell.setCellValue(resultSet.getString("Name"));
                cell = row.createCell(2);
                cell.setCellValue(resultSet.getString("rank_"));
                cell = row.createCell(3);
                cell.setCellValue(resultSet.getString("company"));
                cell = row.createCell(4);
                cell.setCellValue(resultSet.getString("Courses_done"));
                cell = row.createCell(5);
                cell.setCellValue(resultSet.getString("address"));
                cell = row.createCell(6);
                cell.setCellValue(resultSet.getString("Indl_Contact_no"));
                cell = row.createCell(7);
                cell.setCellValue(resultSet.getString("Birth_date"));
                cell = row.createCell(8);
                cell.setCellValue(resultSet.getString("Joining_date"));
                cell = row.createCell(9);
                cell.setCellValue(resultSet.getString("Medical_category"));
                cell = row.createCell(10);
                cell.setCellValue(resultSet.getString("Indl_Icard_Number"));
                cell = row.createCell(11);
                cell.setCellValue(resultSet.getString("Indl_Pan"));
                cell = row.createCell(12);
                cell.setCellValue(resultSet.getString("Indl_aadhar"));
                cell = row.createCell(13);
                cell.setCellValue(resultSet.getString("Indl_email"));
                cell = row.createCell(14);
                cell.setCellValue(resultSet.getString("Indl_Acc_no"));
                cell = row.createCell(15);
                cell.setCellValue(resultSet.getString("Indl_bank_name"));
                cell = row.createCell(16);
                cell.setCellValue(resultSet.getString("Indl_bank_branch"));
                cell = row.createCell(17);
                cell.setCellValue(resultSet.getString("Indl_IFSC"));
                cell = row.createCell(18);
                cell.setCellValue(resultSet.getString("NOK"));
                cell = row.createCell(19);
                cell.setCellValue(resultSet.getString("Kin_Contact_No"));
                cell = row.createCell(20);
                cell.setCellValue(resultSet.getString("Kin_relation"));
                cell = row.createCell(21);
                cell.setCellValue(resultSet.getString("Kin_Pan"));
                cell = row.createCell(22);
                cell.setCellValue(resultSet.getString("Kin_aadhar"));
                cell = row.createCell(23);
                cell.setCellValue(resultSet.getString("Kin_email"));
                cell = row.createCell(24);
                cell.setCellValue(resultSet.getString("Kin_Acc_no"));
                cell = row.createCell(25);
                cell.setCellValue(resultSet.getString("Kin_bank_name"));
                cell = row.createCell(26);
                cell.setCellValue(resultSet.getString("Kin_bank_branch"));
                cell = row.createCell(27);
                cell.setCellValue(resultSet.getString("Kin_IFSC"));
                cell = row.createCell(28);
                cell.setCellValue(resultSet.getString("Retirement_date"));
                i++;
            }
            path_file paths = new path_file();
            FileOutputStream out = new FileOutputStream(new File(paths.csv + "\\Pension_out.xlsx"));
            workbook.write(out);
            System.out.println("Pension_out.xlsx written successfully");
            Desktop.getDesktop().open(new File(paths.csv + "/Pension_out.xlsx"));

        } catch (Exception e) {
            System.err.format("Error! Cannot Print.", e.getMessage());
        }
    }//GEN-LAST:event_print_buttonAMouseClicked

    private void print_buttonAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_buttonAMouseExited
        print_buttonA.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_print_buttonAMouseExited

    private void refresh_buttonAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refresh_buttonAMouseEntered
        refresh_buttonA.setBackground(new java.awt.Color(237, 224, 255));
    }//GEN-LAST:event_refresh_buttonAMouseEntered

    private void refresh_buttonAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refresh_buttonAMouseExited
        refresh_buttonA.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_refresh_buttonAMouseExited

    private void add_buttonBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonBMouseEntered
        add_buttonB.setBackground(new java.awt.Color(237, 224, 255));
    }//GEN-LAST:event_add_buttonBMouseEntered

    private void add_buttonBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonBMouseExited
        add_buttonB.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_add_buttonBMouseExited

    private void fullscreen_buttonAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullscreen_buttonAMouseEntered
        fullscreen_buttonA.setBackground(new java.awt.Color(237, 224, 255));
    }//GEN-LAST:event_fullscreen_buttonAMouseEntered

    private void fullscreen_buttonAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullscreen_buttonAMouseExited
        fullscreen_buttonA.setBackground(new java.awt.Color(240, 240, 240));
    }//GEN-LAST:event_fullscreen_buttonAMouseExited

    private void service_numberAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_service_numberAKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            okayAMouseClicked(null);
        }
    }//GEN-LAST:event_service_numberAKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pension_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pension_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pension_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pension_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pension_Out().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DOB;
    private javax.swing.JLabel DOB_label;
    private javax.swing.JComboBox<String> DOR_date_comboboxA;
    private javax.swing.JLabel DOR_label;
    private javax.swing.JComboBox<String> DOR_month_comboboxA;
    private javax.swing.JComboBox<String> DOR_year_comboboxA;
    private javax.swing.JScrollPane ScrollPaneA;
    private javax.swing.JSeparator Separator;
    private javax.swing.JTable Table;
    private javax.swing.JPanel add_buttonB;
    private javax.swing.JLabel add_labelB;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel exit_fullscreen_button;
    private javax.swing.JLabel exit_fullscreen_label;
    private javax.swing.JLabel exit_icon;
    private javax.swing.JScrollPane fullscreen_ScrollPane;
    private javax.swing.JPanel fullscreen_buttonA;
    private javax.swing.JLabel fullscreen_labelA;
    private javax.swing.JPanel fullscreen_panel;
    private javax.swing.JTable fullscreen_table;
    private javax.swing.JLabel go_back_label;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menuA;
    private javax.swing.JLabel menuA_icon;
    private javax.swing.JLabel menuA_label;
    private javax.swing.JPanel menuB;
    private javax.swing.JLabel menuB_icon;
    private javax.swing.JLabel menuB_label;
    private javax.swing.JLabel minimize_icon;
    private javax.swing.JPanel move_panel;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel okayA;
    private javax.swing.JPanel panelA;
    private javax.swing.JPanel panelB;
    private javax.swing.JPanel print_buttonA;
    private javax.swing.JLabel print_labelD;
    private javax.swing.JPanel refresh_buttonA;
    private javax.swing.JLabel refresh_labelD;
    private javax.swing.JTextField service_numberA;
    private javax.swing.JLabel service_number_label;
    private javax.swing.JPanel side_pane;
    private javax.swing.JSeparator textfield_underlineA;
    private javax.swing.JLabel title_icon;
    private javax.swing.JLabel title_label;
    // End of variables declaration//GEN-END:variables
}
